//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GWRCriteria_Criteria_EventFieldToCompareToSrc.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GWRCriteria_Criteria_EventFieldToCompareToSrc">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="F"/>
 *     &lt;enumeration value="s"/>
 *     &lt;maxLength value="1"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "GWRCriteria_Criteria_EventFieldToCompareToSrc")
@XmlEnum
public enum GWRCriteriaCriteriaEventFieldToCompareToSrc {

    F("F"),
    @XmlEnumValue("s")
    S("s");
    private final String value;

    GWRCriteriaCriteriaEventFieldToCompareToSrc(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GWRCriteriaCriteriaEventFieldToCompareToSrc fromValue(String v) {
        for (GWRCriteriaCriteriaEventFieldToCompareToSrc c: GWRCriteriaCriteriaEventFieldToCompareToSrc.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
