//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GWRCommonCapability.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GWRCommonCapability">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="e4"/>
 *     &lt;enumeration value="e1"/>
 *     &lt;enumeration value="e2"/>
 *     &lt;enumeration value="e3"/>
 *     &lt;enumeration value="e5"/>
 *     &lt;enumeration value="f1"/>
 *     &lt;enumeration value="p1"/>
 *     &lt;enumeration value="s1"/>
 *     &lt;enumeration value="t1"/>
 *     &lt;enumeration value="t2"/>
 *     &lt;enumeration value="u1"/>
 *     &lt;enumeration value="d2"/>
 *     &lt;enumeration value="d1"/>
 *     &lt;enumeration value="v1"/>
 *     &lt;enumeration value="w1"/>
 *     &lt;enumeration value="w2"/>
 *     &lt;maxLength value="2"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "GWRCommonCapability")
@XmlEnum
public enum GWRCommonCapability {

    @XmlEnumValue("e4")
    E_4("e4"),
    @XmlEnumValue("e1")
    E_1("e1"),
    @XmlEnumValue("e2")
    E_2("e2"),
    @XmlEnumValue("e3")
    E_3("e3"),
    @XmlEnumValue("e5")
    E_5("e5"),
    @XmlEnumValue("f1")
    F_1("f1"),
    @XmlEnumValue("p1")
    P_1("p1"),
    @XmlEnumValue("s1")
    S_1("s1"),
    @XmlEnumValue("t1")
    T_1("t1"),
    @XmlEnumValue("t2")
    T_2("t2"),
    @XmlEnumValue("u1")
    U_1("u1"),
    @XmlEnumValue("d2")
    D_2("d2"),
    @XmlEnumValue("d1")
    D_1("d1"),
    @XmlEnumValue("v1")
    V_1("v1"),
    @XmlEnumValue("w1")
    W_1("w1"),
    @XmlEnumValue("w2")
    W_2("w2");
    private final String value;

    GWRCommonCapability(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GWRCommonCapability fromValue(String v) {
        for (GWRCommonCapability c: GWRCommonCapability.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
