//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.common;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * FDS14 - Account processing (PG) - removed BranchNumber, BasicNumber, Suffix.
 * 
 * <p>Java class for GWRFacility complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GWRFacility">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Product" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRProduct" minOccurs="0"/>
 *         &lt;element name="ProductSubType" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRProductTypeCode" minOccurs="0"/>
 *         &lt;element name="MasterReference" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRReference" minOccurs="0"/>
 *         &lt;element name="EventReference" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWREventReference" minOccurs="0"/>
 *         &lt;element name="AccountNumber" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAccountKey" minOccurs="0"/>
 *         &lt;element name="BackOfficeAccount" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAccountNumber" minOccurs="0"/>
 *         &lt;element name="ExternalAccount" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAccountNumber" minOccurs="0"/>
 *         &lt;element name="IBAN" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRIban" minOccurs="0"/>
 *         &lt;element name="AccountType" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAccountTypeCode" minOccurs="0"/>
 *         &lt;element name="Customer" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRCustomerMnemonic" minOccurs="0"/>
 *         &lt;element name="Branch" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRBranchCode" minOccurs="0"/>
 *         &lt;element name="CustomerType" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRCustomerTypeCode" minOccurs="0"/>
 *         &lt;element name="RelatedParty" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRCustomerMnemonic" minOccurs="0"/>
 *         &lt;element name="PostingAmount" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRMoneyNew" minOccurs="0"/>
 *         &lt;element name="DebitCreditFlag" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDebitCredit" minOccurs="0"/>
 *         &lt;element name="ValueDate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDate" minOccurs="0"/>
 *         &lt;element name="TenorStartDate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDate" minOccurs="0"/>
 *         &lt;element name="TenorEndDate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDate" minOccurs="0"/>
 *         &lt;element name="Narrative" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRText4x35" minOccurs="0"/>
 *         &lt;element name="UserCodes" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRUserCodes" minOccurs="0"/>
 *         &lt;element name="BankCode1" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRUserOptionCode" minOccurs="0"/>
 *         &lt;element name="BankCode2" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRUserOptionCode" minOccurs="0"/>
 *         &lt;element name="BankCode3" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRUserOptionCode" minOccurs="0"/>
 *         &lt;element name="BankCode4" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRUserOptionCode" minOccurs="0"/>
 *         &lt;element name="BankCode5" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRUserOptionCode" minOccurs="0"/>
 *         &lt;element name="PostingKey" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAutokeyString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GWRFacility", propOrder = {
    "product",
    "productSubType",
    "masterReference",
    "eventReference",
    "accountNumber",
    "backOfficeAccount",
    "externalAccount",
    "iban",
    "accountType",
    "customer",
    "branch",
    "customerType",
    "relatedParty",
    "postingAmount",
    "debitCreditFlag",
    "valueDate",
    "tenorStartDate",
    "tenorEndDate",
    "narrative",
    "userCodes",
    "bankCode1",
    "bankCode2",
    "bankCode3",
    "bankCode4",
    "bankCode5",
    "postingKey"
})
@XmlSeeAlso({
    GWRReservation.class
})
public class GWRFacility {

    @XmlElement(name = "Product")
    protected String product;
    @XmlElement(name = "ProductSubType")
    protected String productSubType;
    @XmlElement(name = "MasterReference")
    protected String masterReference;
    @XmlElement(name = "EventReference")
    protected String eventReference;
    @XmlElement(name = "AccountNumber")
    protected String accountNumber;
    @XmlElement(name = "BackOfficeAccount")
    protected String backOfficeAccount;
    @XmlElement(name = "ExternalAccount")
    protected String externalAccount;
    @XmlElement(name = "IBAN")
    protected String iban;
    @XmlElement(name = "AccountType")
    protected String accountType;
    @XmlElement(name = "Customer")
    protected String customer;
    @XmlElement(name = "Branch")
    protected String branch;
    @XmlElement(name = "CustomerType")
    protected String customerType;
    @XmlElement(name = "RelatedParty")
    protected String relatedParty;
    @XmlElement(name = "PostingAmount")
    protected GWRMoneyNew postingAmount;
    @XmlElementRef(name = "DebitCreditFlag", namespace = "urn:common.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<GWRDebitCredit> debitCreditFlag;
    @XmlElementRef(name = "ValueDate", namespace = "urn:common.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> valueDate;
    @XmlElementRef(name = "TenorStartDate", namespace = "urn:common.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> tenorStartDate;
    @XmlElementRef(name = "TenorEndDate", namespace = "urn:common.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> tenorEndDate;
    @XmlElement(name = "Narrative")
    protected String narrative;
    @XmlElement(name = "UserCodes")
    protected String userCodes;
    @XmlElement(name = "BankCode1")
    protected String bankCode1;
    @XmlElement(name = "BankCode2")
    protected String bankCode2;
    @XmlElement(name = "BankCode3")
    protected String bankCode3;
    @XmlElement(name = "BankCode4")
    protected String bankCode4;
    @XmlElement(name = "BankCode5")
    protected String bankCode5;
    @XmlElement(name = "PostingKey")
    protected String postingKey;

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProduct(String value) {
        this.product = value;
    }

    /**
     * Gets the value of the productSubType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductSubType() {
        return productSubType;
    }

    /**
     * Sets the value of the productSubType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductSubType(String value) {
        this.productSubType = value;
    }

    /**
     * Gets the value of the masterReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterReference() {
        return masterReference;
    }

    /**
     * Sets the value of the masterReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterReference(String value) {
        this.masterReference = value;
    }

    /**
     * Gets the value of the eventReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventReference() {
        return eventReference;
    }

    /**
     * Sets the value of the eventReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventReference(String value) {
        this.eventReference = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the backOfficeAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackOfficeAccount() {
        return backOfficeAccount;
    }

    /**
     * Sets the value of the backOfficeAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackOfficeAccount(String value) {
        this.backOfficeAccount = value;
    }

    /**
     * Gets the value of the externalAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalAccount() {
        return externalAccount;
    }

    /**
     * Sets the value of the externalAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalAccount(String value) {
        this.externalAccount = value;
    }

    /**
     * Gets the value of the iban property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIBAN() {
        return iban;
    }

    /**
     * Sets the value of the iban property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIBAN(String value) {
        this.iban = value;
    }

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountType(String value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomer(String value) {
        this.customer = value;
    }

    /**
     * Gets the value of the branch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranch() {
        return branch;
    }

    /**
     * Sets the value of the branch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranch(String value) {
        this.branch = value;
    }

    /**
     * Gets the value of the customerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * Sets the value of the customerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerType(String value) {
        this.customerType = value;
    }

    /**
     * Gets the value of the relatedParty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedParty() {
        return relatedParty;
    }

    /**
     * Sets the value of the relatedParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedParty(String value) {
        this.relatedParty = value;
    }

    /**
     * Gets the value of the postingAmount property.
     * 
     * @return
     *     possible object is
     *     {@link GWRMoneyNew }
     *     
     */
    public GWRMoneyNew getPostingAmount() {
        return postingAmount;
    }

    /**
     * Sets the value of the postingAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRMoneyNew }
     *     
     */
    public void setPostingAmount(GWRMoneyNew value) {
        this.postingAmount = value;
    }

    /**
     * Gets the value of the debitCreditFlag property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GWRDebitCredit }{@code >}
     *     
     */
    public JAXBElement<GWRDebitCredit> getDebitCreditFlag() {
        return debitCreditFlag;
    }

    /**
     * Sets the value of the debitCreditFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GWRDebitCredit }{@code >}
     *     
     */
    public void setDebitCreditFlag(JAXBElement<GWRDebitCredit> value) {
        this.debitCreditFlag = ((JAXBElement<GWRDebitCredit> ) value);
    }

    /**
     * Gets the value of the valueDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getValueDate() {
        return valueDate;
    }

    /**
     * Sets the value of the valueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setValueDate(JAXBElement<XMLGregorianCalendar> value) {
        this.valueDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the tenorStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getTenorStartDate() {
        return tenorStartDate;
    }

    /**
     * Sets the value of the tenorStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setTenorStartDate(JAXBElement<XMLGregorianCalendar> value) {
        this.tenorStartDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the tenorEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getTenorEndDate() {
        return tenorEndDate;
    }

    /**
     * Sets the value of the tenorEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setTenorEndDate(JAXBElement<XMLGregorianCalendar> value) {
        this.tenorEndDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the narrative property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNarrative() {
        return narrative;
    }

    /**
     * Sets the value of the narrative property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNarrative(String value) {
        this.narrative = value;
    }

    /**
     * Gets the value of the userCodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserCodes() {
        return userCodes;
    }

    /**
     * Sets the value of the userCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserCodes(String value) {
        this.userCodes = value;
    }

    /**
     * Gets the value of the bankCode1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankCode1() {
        return bankCode1;
    }

    /**
     * Sets the value of the bankCode1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankCode1(String value) {
        this.bankCode1 = value;
    }

    /**
     * Gets the value of the bankCode2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankCode2() {
        return bankCode2;
    }

    /**
     * Sets the value of the bankCode2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankCode2(String value) {
        this.bankCode2 = value;
    }

    /**
     * Gets the value of the bankCode3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankCode3() {
        return bankCode3;
    }

    /**
     * Sets the value of the bankCode3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankCode3(String value) {
        this.bankCode3 = value;
    }

    /**
     * Gets the value of the bankCode4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankCode4() {
        return bankCode4;
    }

    /**
     * Sets the value of the bankCode4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankCode4(String value) {
        this.bankCode4 = value;
    }

    /**
     * Gets the value of the bankCode5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankCode5() {
        return bankCode5;
    }

    /**
     * Sets the value of the bankCode5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankCode5(String value) {
        this.bankCode5 = value;
    }

    /**
     * Gets the value of the postingKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostingKey() {
        return postingKey;
    }

    /**
     * Sets the value of the postingKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostingKey(String value) {
        this.postingKey = value;
    }

}
