//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.common;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GWRInterestScheduleTier complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GWRInterestScheduleTier">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InterestTierBasic" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRInterestTierBasic" minOccurs="0"/>
 *         &lt;element name="BaseRate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRBaseRateCode" minOccurs="0"/>
 *         &lt;element name="DifferentialRate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDifferentialRate" minOccurs="0"/>
 *         &lt;element name="GroupRate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRGroupRate" minOccurs="0"/>
 *         &lt;element name="Rate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRRate" minOccurs="0"/>
 *         &lt;element name="SpreadRate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRRate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GWRInterestScheduleTier", propOrder = {
    "interestTierBasic",
    "baseRate",
    "differentialRate",
    "groupRate",
    "rate",
    "spreadRate"
})
public class GWRInterestScheduleTier {

    @XmlElement(name = "InterestTierBasic")
    protected GWRInterestTierBasic interestTierBasic;
    @XmlElement(name = "BaseRate")
    protected String baseRate;
    @XmlElement(name = "DifferentialRate")
    protected String differentialRate;
    @XmlElementRef(name = "GroupRate", namespace = "urn:common.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<String> groupRate;
    @XmlElement(name = "Rate")
    protected BigDecimal rate;
    @XmlElement(name = "SpreadRate")
    protected BigDecimal spreadRate;

    /**
     * Gets the value of the interestTierBasic property.
     * 
     * @return
     *     possible object is
     *     {@link GWRInterestTierBasic }
     *     
     */
    public GWRInterestTierBasic getInterestTierBasic() {
        return interestTierBasic;
    }

    /**
     * Sets the value of the interestTierBasic property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRInterestTierBasic }
     *     
     */
    public void setInterestTierBasic(GWRInterestTierBasic value) {
        this.interestTierBasic = value;
    }

    /**
     * Gets the value of the baseRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseRate() {
        return baseRate;
    }

    /**
     * Sets the value of the baseRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseRate(String value) {
        this.baseRate = value;
    }

    /**
     * Gets the value of the differentialRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDifferentialRate() {
        return differentialRate;
    }

    /**
     * Sets the value of the differentialRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDifferentialRate(String value) {
        this.differentialRate = value;
    }

    /**
     * Gets the value of the groupRate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getGroupRate() {
        return groupRate;
    }

    /**
     * Sets the value of the groupRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setGroupRate(JAXBElement<String> value) {
        this.groupRate = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the rate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * Sets the value of the rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRate(BigDecimal value) {
        this.rate = value;
    }

    /**
     * Gets the value of the spreadRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSpreadRate() {
        return spreadRate;
    }

    /**
     * Sets the value of the spreadRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSpreadRate(BigDecimal value) {
        this.spreadRate = value;
    }

}
