//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.common;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for GWRRollingRenewal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GWRRollingRenewal">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CancellationNotice" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRInteger" minOccurs="0"/>
 *         &lt;element name="EveryPEriod" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRPeriodAndDayInMonth" minOccurs="0"/>
 *         &lt;element name="NumberOf" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRInteger" minOccurs="0"/>
 *         &lt;element name="RenewOn" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRRenewOn" minOccurs="0"/>
 *         &lt;element name="AdjustedFinalExpiryDate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GWRRollingRenewal", propOrder = {
    "cancellationNotice",
    "everyPEriod",
    "numberOf",
    "renewOn",
    "adjustedFinalExpiryDate"
})
public class GWRRollingRenewal {

    @XmlElementRef(name = "CancellationNotice", namespace = "urn:common.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Integer> cancellationNotice;
    @XmlElement(name = "EveryPEriod")
    protected GWRPeriodAndDayInMonth everyPEriod;
    @XmlElementRef(name = "NumberOf", namespace = "urn:common.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Integer> numberOf;
    @XmlElement(name = "RenewOn")
    protected GWRRenewOn renewOn;
    @XmlElementRef(name = "AdjustedFinalExpiryDate", namespace = "urn:common.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> adjustedFinalExpiryDate;

    /**
     * Gets the value of the cancellationNotice property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getCancellationNotice() {
        return cancellationNotice;
    }

    /**
     * Sets the value of the cancellationNotice property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setCancellationNotice(JAXBElement<Integer> value) {
        this.cancellationNotice = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the everyPEriod property.
     * 
     * @return
     *     possible object is
     *     {@link GWRPeriodAndDayInMonth }
     *     
     */
    public GWRPeriodAndDayInMonth getEveryPEriod() {
        return everyPEriod;
    }

    /**
     * Sets the value of the everyPEriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRPeriodAndDayInMonth }
     *     
     */
    public void setEveryPEriod(GWRPeriodAndDayInMonth value) {
        this.everyPEriod = value;
    }

    /**
     * Gets the value of the numberOf property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getNumberOf() {
        return numberOf;
    }

    /**
     * Sets the value of the numberOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setNumberOf(JAXBElement<Integer> value) {
        this.numberOf = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the renewOn property.
     * 
     * @return
     *     possible object is
     *     {@link GWRRenewOn }
     *     
     */
    public GWRRenewOn getRenewOn() {
        return renewOn;
    }

    /**
     * Sets the value of the renewOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRRenewOn }
     *     
     */
    public void setRenewOn(GWRRenewOn value) {
        this.renewOn = value;
    }

    /**
     * Gets the value of the adjustedFinalExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getAdjustedFinalExpiryDate() {
        return adjustedFinalExpiryDate;
    }

    /**
     * Sets the value of the adjustedFinalExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setAdjustedFinalExpiryDate(JAXBElement<XMLGregorianCalendar> value) {
        this.adjustedFinalExpiryDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

}
