//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.common;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GWRSLADetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GWRSLADetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DashboardDetail" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Zone" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="20"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Event" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="20"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Product" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="10"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="EventType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="StepKey" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="20"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Via" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRSLADetails_SLADashboardDetail_CreationMethod" minOccurs="0"/>
 *                   &lt;element name="OurReference" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="26"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="MasterKeyS" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="20"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="MasterReference" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="20"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="EventPrefix" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="3"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="EventSerial" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="TheirReference" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="20"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Customer" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="20"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CustomerAddressLine" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="35"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Amount" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="23"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Team" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="15"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="User" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="20"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Step" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Deadline" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="SLAName" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="20"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RAGStatus" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRSLADetails_SLADashboardDetail_RAGStatus" minOccurs="0"/>
 *                   &lt;element name="CreationDate" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="10"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RedTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="AmberTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GWRSLADetails", propOrder = {
    "dashboardDetail"
})
public class GWRSLADetails {

    @XmlElement(name = "DashboardDetail", required = true)
    protected List<GWRSLADetails.DashboardDetail> dashboardDetail;

    /**
     * Gets the value of the dashboardDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dashboardDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDashboardDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GWRSLADetails.DashboardDetail }
     * 
     * 
     */
    public List<GWRSLADetails.DashboardDetail> getDashboardDetail() {
        if (dashboardDetail == null) {
            dashboardDetail = new ArrayList<GWRSLADetails.DashboardDetail>();
        }
        return this.dashboardDetail;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Zone" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Event" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Product" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="10"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="EventType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="StepKey" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Via" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRSLADetails_SLADashboardDetail_CreationMethod" minOccurs="0"/>
     *         &lt;element name="OurReference" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="26"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="MasterKeyS" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="MasterReference" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="EventPrefix" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="3"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="EventSerial" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="TheirReference" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Customer" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CustomerAddressLine" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="35"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Amount" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="23"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Team" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="15"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="User" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Step" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Deadline" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="SLAName" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RAGStatus" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRSLADetails_SLADashboardDetail_RAGStatus" minOccurs="0"/>
     *         &lt;element name="CreationDate" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="10"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RedTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="AmberTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "zone",
        "event",
        "product",
        "eventType",
        "stepKey",
        "via",
        "ourReference",
        "masterKeyS",
        "masterReference",
        "eventPrefix",
        "eventSerial",
        "theirReference",
        "customer",
        "customerAddressLine",
        "amount",
        "team",
        "user",
        "status",
        "step",
        "deadline",
        "slaName",
        "ragStatus",
        "creationDate",
        "redTime",
        "amberTime"
    })
    public static class DashboardDetail {

        @XmlElement(name = "Zone")
        protected String zone;
        @XmlElement(name = "Event")
        protected String event;
        @XmlElement(name = "Product")
        protected String product;
        @XmlElement(name = "EventType")
        protected String eventType;
        @XmlElement(name = "StepKey")
        protected String stepKey;
        @XmlElementRef(name = "Via", namespace = "urn:common.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
        protected JAXBElement<GWRSLADetailsSLADashboardDetailCreationMethod> via;
        @XmlElement(name = "OurReference")
        protected String ourReference;
        @XmlElement(name = "MasterKeyS")
        protected String masterKeyS;
        @XmlElementRef(name = "MasterReference", namespace = "urn:common.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
        protected JAXBElement<String> masterReference;
        @XmlElement(name = "EventPrefix")
        protected String eventPrefix;
        @XmlElementRef(name = "EventSerial", namespace = "urn:common.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
        protected JAXBElement<Integer> eventSerial;
        @XmlElementRef(name = "TheirReference", namespace = "urn:common.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
        protected JAXBElement<String> theirReference;
        @XmlElementRef(name = "Customer", namespace = "urn:common.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
        protected JAXBElement<String> customer;
        @XmlElement(name = "CustomerAddressLine")
        protected String customerAddressLine;
        @XmlElement(name = "Amount")
        protected String amount;
        @XmlElementRef(name = "Team", namespace = "urn:common.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
        protected JAXBElement<String> team;
        @XmlElementRef(name = "User", namespace = "urn:common.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
        protected JAXBElement<String> user;
        @XmlElement(name = "Status")
        protected String status;
        @XmlElement(name = "Step")
        protected String step;
        @XmlElement(name = "Deadline")
        protected String deadline;
        @XmlElementRef(name = "SLAName", namespace = "urn:common.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
        protected JAXBElement<String> slaName;
        @XmlElement(name = "RAGStatus")
        protected GWRSLADetailsSLADashboardDetailRAGStatus ragStatus;
        @XmlElement(name = "CreationDate")
        protected String creationDate;
        @XmlElement(name = "RedTime")
        protected String redTime;
        @XmlElement(name = "AmberTime")
        protected String amberTime;

        /**
         * Gets the value of the zone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZone() {
            return zone;
        }

        /**
         * Sets the value of the zone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZone(String value) {
            this.zone = value;
        }

        /**
         * Gets the value of the event property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEvent() {
            return event;
        }

        /**
         * Sets the value of the event property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEvent(String value) {
            this.event = value;
        }

        /**
         * Gets the value of the product property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProduct() {
            return product;
        }

        /**
         * Sets the value of the product property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProduct(String value) {
            this.product = value;
        }

        /**
         * Gets the value of the eventType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEventType() {
            return eventType;
        }

        /**
         * Sets the value of the eventType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEventType(String value) {
            this.eventType = value;
        }

        /**
         * Gets the value of the stepKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStepKey() {
            return stepKey;
        }

        /**
         * Sets the value of the stepKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStepKey(String value) {
            this.stepKey = value;
        }

        /**
         * Gets the value of the via property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link GWRSLADetailsSLADashboardDetailCreationMethod }{@code >}
         *     
         */
        public JAXBElement<GWRSLADetailsSLADashboardDetailCreationMethod> getVia() {
            return via;
        }

        /**
         * Sets the value of the via property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link GWRSLADetailsSLADashboardDetailCreationMethod }{@code >}
         *     
         */
        public void setVia(JAXBElement<GWRSLADetailsSLADashboardDetailCreationMethod> value) {
            this.via = ((JAXBElement<GWRSLADetailsSLADashboardDetailCreationMethod> ) value);
        }

        /**
         * Gets the value of the ourReference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOurReference() {
            return ourReference;
        }

        /**
         * Sets the value of the ourReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOurReference(String value) {
            this.ourReference = value;
        }

        /**
         * Gets the value of the masterKeyS property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMasterKeyS() {
            return masterKeyS;
        }

        /**
         * Sets the value of the masterKeyS property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMasterKeyS(String value) {
            this.masterKeyS = value;
        }

        /**
         * Gets the value of the masterReference property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public JAXBElement<String> getMasterReference() {
            return masterReference;
        }

        /**
         * Sets the value of the masterReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setMasterReference(JAXBElement<String> value) {
            this.masterReference = ((JAXBElement<String> ) value);
        }

        /**
         * Gets the value of the eventPrefix property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEventPrefix() {
            return eventPrefix;
        }

        /**
         * Sets the value of the eventPrefix property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEventPrefix(String value) {
            this.eventPrefix = value;
        }

        /**
         * Gets the value of the eventSerial property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
         *     
         */
        public JAXBElement<Integer> getEventSerial() {
            return eventSerial;
        }

        /**
         * Sets the value of the eventSerial property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
         *     
         */
        public void setEventSerial(JAXBElement<Integer> value) {
            this.eventSerial = ((JAXBElement<Integer> ) value);
        }

        /**
         * Gets the value of the theirReference property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public JAXBElement<String> getTheirReference() {
            return theirReference;
        }

        /**
         * Sets the value of the theirReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setTheirReference(JAXBElement<String> value) {
            this.theirReference = ((JAXBElement<String> ) value);
        }

        /**
         * Gets the value of the customer property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public JAXBElement<String> getCustomer() {
            return customer;
        }

        /**
         * Sets the value of the customer property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setCustomer(JAXBElement<String> value) {
            this.customer = ((JAXBElement<String> ) value);
        }

        /**
         * Gets the value of the customerAddressLine property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustomerAddressLine() {
            return customerAddressLine;
        }

        /**
         * Sets the value of the customerAddressLine property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustomerAddressLine(String value) {
            this.customerAddressLine = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAmount(String value) {
            this.amount = value;
        }

        /**
         * Gets the value of the team property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public JAXBElement<String> getTeam() {
            return team;
        }

        /**
         * Sets the value of the team property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setTeam(JAXBElement<String> value) {
            this.team = ((JAXBElement<String> ) value);
        }

        /**
         * Gets the value of the user property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public JAXBElement<String> getUser() {
            return user;
        }

        /**
         * Sets the value of the user property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setUser(JAXBElement<String> value) {
            this.user = ((JAXBElement<String> ) value);
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the step property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStep() {
            return step;
        }

        /**
         * Sets the value of the step property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStep(String value) {
            this.step = value;
        }

        /**
         * Gets the value of the deadline property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeadline() {
            return deadline;
        }

        /**
         * Sets the value of the deadline property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeadline(String value) {
            this.deadline = value;
        }

        /**
         * Gets the value of the slaName property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public JAXBElement<String> getSLAName() {
            return slaName;
        }

        /**
         * Sets the value of the slaName property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setSLAName(JAXBElement<String> value) {
            this.slaName = ((JAXBElement<String> ) value);
        }

        /**
         * Gets the value of the ragStatus property.
         * 
         * @return
         *     possible object is
         *     {@link GWRSLADetailsSLADashboardDetailRAGStatus }
         *     
         */
        public GWRSLADetailsSLADashboardDetailRAGStatus getRAGStatus() {
            return ragStatus;
        }

        /**
         * Sets the value of the ragStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link GWRSLADetailsSLADashboardDetailRAGStatus }
         *     
         */
        public void setRAGStatus(GWRSLADetailsSLADashboardDetailRAGStatus value) {
            this.ragStatus = value;
        }

        /**
         * Gets the value of the creationDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCreationDate() {
            return creationDate;
        }

        /**
         * Sets the value of the creationDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCreationDate(String value) {
            this.creationDate = value;
        }

        /**
         * Gets the value of the redTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRedTime() {
            return redTime;
        }

        /**
         * Sets the value of the redTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRedTime(String value) {
            this.redTime = value;
        }

        /**
         * Gets the value of the amberTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAmberTime() {
            return amberTime;
        }

        /**
         * Sets the value of the amberTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAmberTime(String value) {
            this.amberTime = value;
        }

    }

}
