//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.16 at 03:54:00 PM IST 
//


package com.misys.tiplus2.apps.ti.service.custom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Account Realisation
 * 
 * <p>Java class for ExtEventAccountRealisationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtEventAccountRealisationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RACCOUNT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RACCTTYP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RAMOUNT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RPERCENT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtEventAccountRealisationType", propOrder = {
    "raccount",
    "raccttyp",
    "ramount",
    "rpercent"
})
public class ExtEventAccountRealisationType {

    @XmlElement(name = "RACCOUNT")
    protected String raccount;
    @XmlElement(name = "RACCTTYP")
    protected String raccttyp;
    @XmlElement(name = "RAMOUNT")
    protected String ramount;
    @XmlElement(name = "RPERCENT")
    protected String rpercent;

    /**
     * Gets the value of the raccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRACCOUNT() {
        return raccount;
    }

    /**
     * Sets the value of the raccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRACCOUNT(String value) {
        this.raccount = value;
    }

    /**
     * Gets the value of the raccttyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRACCTTYP() {
        return raccttyp;
    }

    /**
     * Sets the value of the raccttyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRACCTTYP(String value) {
        this.raccttyp = value;
    }

    /**
     * Gets the value of the ramount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRAMOUNT() {
        return ramount;
    }

    /**
     * Sets the value of the ramount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRAMOUNT(String value) {
        this.ramount = value;
    }

    /**
     * Gets the value of the rpercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRPERCENT() {
        return rpercent;
    }

    /**
     * Sets the value of the rpercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRPERCENT(String value) {
        this.rpercent = value;
    }

}
