//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.16 at 03:54:00 PM IST 
//


package com.misys.tiplus2.apps.ti.service.custom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Preshipment
 * 
 * <p>Java class for ExtEventPreshipmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtEventPreshipmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LOANNO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="REPREF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="REPYAMNT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtEventPreshipmentType", propOrder = {
    "loanno",
    "repref",
    "repyamnt"
})
public class ExtEventPreshipmentType {

    @XmlElement(name = "LOANNO")
    protected String loanno;
    @XmlElement(name = "REPREF")
    protected String repref;
    @XmlElement(name = "REPYAMNT")
    protected String repyamnt;

    /**
     * Gets the value of the loanno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOANNO() {
        return loanno;
    }

    /**
     * Sets the value of the loanno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOANNO(String value) {
        this.loanno = value;
    }

    /**
     * Gets the value of the repref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREPREF() {
        return repref;
    }

    /**
     * Sets the value of the repref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREPREF(String value) {
        this.repref = value;
    }

    /**
     * Gets the value of the repyamnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREPYAMNT() {
        return repyamnt;
    }

    /**
     * Sets the value of the repyamnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREPYAMNT(String value) {
        this.repyamnt = value;
    }

}
