//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.16 at 03:54:00 PM IST 
//


package com.misys.tiplus2.apps.ti.service.custom;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Firc Details
 * 
 * <p>Java class for ExtEventFircDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtEventFircDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FRNUMB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FIRCDT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FRCUTA" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="FIRCCU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtEventFircDetailsType", propOrder = {
    "frnumb",
    "fircdt",
    "frcuta",
    "firccu"
})
public class ExtEventFircDetailsType {

    @XmlElement(name = "FRNUMB")
    protected String frnumb;
    @XmlElement(name = "FIRCDT")
    protected String fircdt;
    @XmlElement(name = "FRCUTA")
    protected BigDecimal frcuta;
    @XmlElement(name = "FIRCCU")
    protected String firccu;

    /**
     * Gets the value of the frnumb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFRNUMB() {
        return frnumb;
    }

    /**
     * Sets the value of the frnumb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFRNUMB(String value) {
        this.frnumb = value;
    }

    /**
     * Gets the value of the fircdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIRCDT() {
        return fircdt;
    }

    /**
     * Sets the value of the fircdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIRCDT(String value) {
        this.fircdt = value;
    }

    /**
     * Gets the value of the frcuta property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFRCUTA() {
        return frcuta;
    }

    /**
     * Sets the value of the frcuta property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFRCUTA(BigDecimal value) {
        this.frcuta = value;
    }

    /**
     * Gets the value of the firccu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIRCCU() {
        return firccu;
    }

    /**
     * Sets the value of the firccu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIRCCU(String value) {
        this.firccu = value;
    }

}
