//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * .
 * 
 * <p>Java class for AttachedDocumentsMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttachedDocumentsMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GWRAttachedDocuments" type="{urn:messages.service.ti.apps.tiplus2.misys.com}GWRAttachedDocuments" minOccurs="0"/>
 *         &lt;element name="Service" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Operation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttachedDocumentsMessage", propOrder = {
    "gwrAttachedDocuments",
    "service",
    "operation"
})
public class AttachedDocumentsMessage {

    @XmlElement(name = "GWRAttachedDocuments")
    protected GWRAttachedDocuments gwrAttachedDocuments;
    @XmlElement(name = "Service")
    protected String service;
    @XmlElement(name = "Operation")
    protected String operation;

    /**
     * Gets the value of the gwrAttachedDocuments property.
     * 
     * @return
     *     possible object is
     *     {@link GWRAttachedDocuments }
     *     
     */
    public GWRAttachedDocuments getGWRAttachedDocuments() {
        return gwrAttachedDocuments;
    }

    /**
     * Sets the value of the gwrAttachedDocuments property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRAttachedDocuments }
     *     
     */
    public void setGWRAttachedDocuments(GWRAttachedDocuments value) {
        this.gwrAttachedDocuments = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setService(String value) {
        this.service = value;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperation(String value) {
        this.operation = value;
    }

}
