//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.messages;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.misys.tiplus2.apps.ti.service.common.EnigmaBoolean;
import com.misys.tiplus2.apps.ti.service.common.GWRBuyerSeller;
import com.misys.tiplus2.apps.ti.service.common.GWRFxRateToUse;
import com.misys.tiplus2.apps.ti.service.common.GWRMoney;


/**
 * New API response pane used to handle FX rate Service .
 * 
 * <p>Java class for FXRateServiceResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FXRateServiceResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrderId" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAutokeyString" minOccurs="0"/>
 *         &lt;element name="DealTicketId" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDealTicketId" minOccurs="0"/>
 *         &lt;element name="DealDirection" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRBuyerSeller" minOccurs="0"/>
 *         &lt;element name="FXRateCode" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRFxRateCode" minOccurs="0"/>
 *         &lt;element name="FXRateType" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRFxRateToUse" minOccurs="0"/>
 *         &lt;element name="Amount1" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRMoney" minOccurs="0"/>
 *         &lt;element name="Amount2" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRMoney" minOccurs="0"/>
 *         &lt;element name="ExchangeRate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRExchangeRate" minOccurs="0"/>
 *         &lt;element name="Reciprocal" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRBool" minOccurs="0"/>
 *         &lt;element name="BuyCurrency" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRCurrency" minOccurs="0"/>
 *         &lt;element name="BuyCurrencyQuotationUnit" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRCurrencyQuotationUnit" minOccurs="0"/>
 *         &lt;element name="BuyRateToBase" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRExchangeRate" minOccurs="0"/>
 *         &lt;element name="SellCurrency" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRCurrency" minOccurs="0"/>
 *         &lt;element name="SellCurrencyQuotationUnit" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRCurrencyQuotationUnit" minOccurs="0"/>
 *         &lt;element name="SellRateToBase" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRExchangeRate" minOccurs="0"/>
 *         &lt;element name="FxRateDate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDate" minOccurs="0"/>
 *         &lt;element name="FxRateTime" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRHoursMinutesSeconds" minOccurs="0"/>
 *         &lt;element name="BaseCurrency" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRCurrency" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FXRateServiceResponse", propOrder = {
    "orderId",
    "dealTicketId",
    "dealDirection",
    "fxRateCode",
    "fxRateType",
    "amount1",
    "amount2",
    "exchangeRate",
    "reciprocal",
    "buyCurrency",
    "buyCurrencyQuotationUnit",
    "buyRateToBase",
    "sellCurrency",
    "sellCurrencyQuotationUnit",
    "sellRateToBase",
    "fxRateDate",
    "fxRateTime",
    "baseCurrency"
})
public class FXRateServiceResponse {

    @XmlElement(name = "OrderId")
    protected String orderId;
    @XmlElement(name = "DealTicketId")
    protected String dealTicketId;
    @XmlElementRef(name = "DealDirection", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<GWRBuyerSeller> dealDirection;
    @XmlElement(name = "FXRateCode")
    protected String fxRateCode;
    @XmlElementRef(name = "FXRateType", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<GWRFxRateToUse> fxRateType;
    @XmlElement(name = "Amount1")
    protected GWRMoney amount1;
    @XmlElement(name = "Amount2")
    protected GWRMoney amount2;
    @XmlElement(name = "ExchangeRate")
    protected String exchangeRate;
    @XmlElement(name = "Reciprocal")
    protected EnigmaBoolean reciprocal;
    @XmlElement(name = "BuyCurrency")
    protected String buyCurrency;
    @XmlElementRef(name = "BuyCurrencyQuotationUnit", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<String> buyCurrencyQuotationUnit;
    @XmlElement(name = "BuyRateToBase")
    protected String buyRateToBase;
    @XmlElement(name = "SellCurrency")
    protected String sellCurrency;
    @XmlElementRef(name = "SellCurrencyQuotationUnit", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<String> sellCurrencyQuotationUnit;
    @XmlElement(name = "SellRateToBase")
    protected String sellRateToBase;
    @XmlElementRef(name = "FxRateDate", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> fxRateDate;
    @XmlElement(name = "FxRateTime")
    protected String fxRateTime;
    @XmlElement(name = "BaseCurrency")
    protected String baseCurrency;

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderId(String value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the dealTicketId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealTicketId() {
        return dealTicketId;
    }

    /**
     * Sets the value of the dealTicketId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealTicketId(String value) {
        this.dealTicketId = value;
    }

    /**
     * Gets the value of the dealDirection property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GWRBuyerSeller }{@code >}
     *     
     */
    public JAXBElement<GWRBuyerSeller> getDealDirection() {
        return dealDirection;
    }

    /**
     * Sets the value of the dealDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GWRBuyerSeller }{@code >}
     *     
     */
    public void setDealDirection(JAXBElement<GWRBuyerSeller> value) {
        this.dealDirection = ((JAXBElement<GWRBuyerSeller> ) value);
    }

    /**
     * Gets the value of the fxRateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFXRateCode() {
        return fxRateCode;
    }

    /**
     * Sets the value of the fxRateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFXRateCode(String value) {
        this.fxRateCode = value;
    }

    /**
     * Gets the value of the fxRateType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GWRFxRateToUse }{@code >}
     *     
     */
    public JAXBElement<GWRFxRateToUse> getFXRateType() {
        return fxRateType;
    }

    /**
     * Sets the value of the fxRateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GWRFxRateToUse }{@code >}
     *     
     */
    public void setFXRateType(JAXBElement<GWRFxRateToUse> value) {
        this.fxRateType = ((JAXBElement<GWRFxRateToUse> ) value);
    }

    /**
     * Gets the value of the amount1 property.
     * 
     * @return
     *     possible object is
     *     {@link GWRMoney }
     *     
     */
    public GWRMoney getAmount1() {
        return amount1;
    }

    /**
     * Sets the value of the amount1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRMoney }
     *     
     */
    public void setAmount1(GWRMoney value) {
        this.amount1 = value;
    }

    /**
     * Gets the value of the amount2 property.
     * 
     * @return
     *     possible object is
     *     {@link GWRMoney }
     *     
     */
    public GWRMoney getAmount2() {
        return amount2;
    }

    /**
     * Sets the value of the amount2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRMoney }
     *     
     */
    public void setAmount2(GWRMoney value) {
        this.amount2 = value;
    }

    /**
     * Gets the value of the exchangeRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchangeRate() {
        return exchangeRate;
    }

    /**
     * Sets the value of the exchangeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchangeRate(String value) {
        this.exchangeRate = value;
    }

    /**
     * Gets the value of the reciprocal property.
     * 
     * @return
     *     possible object is
     *     {@link EnigmaBoolean }
     *     
     */
    public EnigmaBoolean getReciprocal() {
        return reciprocal;
    }

    /**
     * Sets the value of the reciprocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnigmaBoolean }
     *     
     */
    public void setReciprocal(EnigmaBoolean value) {
        this.reciprocal = value;
    }

    /**
     * Gets the value of the buyCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyCurrency() {
        return buyCurrency;
    }

    /**
     * Sets the value of the buyCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyCurrency(String value) {
        this.buyCurrency = value;
    }

    /**
     * Gets the value of the buyCurrencyQuotationUnit property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBuyCurrencyQuotationUnit() {
        return buyCurrencyQuotationUnit;
    }

    /**
     * Sets the value of the buyCurrencyQuotationUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBuyCurrencyQuotationUnit(JAXBElement<String> value) {
        this.buyCurrencyQuotationUnit = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the buyRateToBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyRateToBase() {
        return buyRateToBase;
    }

    /**
     * Sets the value of the buyRateToBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyRateToBase(String value) {
        this.buyRateToBase = value;
    }

    /**
     * Gets the value of the sellCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellCurrency() {
        return sellCurrency;
    }

    /**
     * Sets the value of the sellCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellCurrency(String value) {
        this.sellCurrency = value;
    }

    /**
     * Gets the value of the sellCurrencyQuotationUnit property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSellCurrencyQuotationUnit() {
        return sellCurrencyQuotationUnit;
    }

    /**
     * Sets the value of the sellCurrencyQuotationUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSellCurrencyQuotationUnit(JAXBElement<String> value) {
        this.sellCurrencyQuotationUnit = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the sellRateToBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellRateToBase() {
        return sellRateToBase;
    }

    /**
     * Sets the value of the sellRateToBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellRateToBase(String value) {
        this.sellRateToBase = value;
    }

    /**
     * Gets the value of the fxRateDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getFxRateDate() {
        return fxRateDate;
    }

    /**
     * Sets the value of the fxRateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setFxRateDate(JAXBElement<XMLGregorianCalendar> value) {
        this.fxRateDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the fxRateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFxRateTime() {
        return fxRateTime;
    }

    /**
     * Sets the value of the fxRateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFxRateTime(String value) {
        this.fxRateTime = value;
    }

    /**
     * Gets the value of the baseCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseCurrency() {
        return baseCurrency;
    }

    /**
     * Sets the value of the baseCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseCurrency(String value) {
        this.baseCurrency = value;
    }

}
