//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import com.misys.tiplus2.apps.ti.service.common.EnigmaBoolean;
import com.misys.tiplus2.apps.ti.service.common.GWRMaintenanceType;


/**
 * <p>Java class for GatewayDataUpdateDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GatewayDataUpdateDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MaintType" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRMaintenanceType" minOccurs="0"/>
 *         &lt;element name="MaintainedInBackOffice" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRBool" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GatewayDataUpdateDefinition", propOrder = {
    "maintType",
    "maintainedInBackOffice"
})
@XmlSeeAlso({
    STRCustomerMnemonic.class,
    STRAccountAndDealBranchChange.class
})
public class GatewayDataUpdateDefinition {

    @XmlElement(name = "MaintType")
    protected GWRMaintenanceType maintType;
    @XmlElement(name = "MaintainedInBackOffice")
    protected EnigmaBoolean maintainedInBackOffice;

    /**
     * Gets the value of the maintType property.
     * 
     * @return
     *     possible object is
     *     {@link GWRMaintenanceType }
     *     
     */
    public GWRMaintenanceType getMaintType() {
        return maintType;
    }

    /**
     * Sets the value of the maintType property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRMaintenanceType }
     *     
     */
    public void setMaintType(GWRMaintenanceType value) {
        this.maintType = value;
    }

    /**
     * Gets the value of the maintainedInBackOffice property.
     * 
     * @return
     *     possible object is
     *     {@link EnigmaBoolean }
     *     
     */
    public EnigmaBoolean getMaintainedInBackOffice() {
        return maintainedInBackOffice;
    }

    /**
     * Sets the value of the maintainedInBackOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnigmaBoolean }
     *     
     */
    public void setMaintainedInBackOffice(EnigmaBoolean value) {
        this.maintainedInBackOffice = value;
    }

}
