//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.messages;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GWR490_GWRCollectionDraftA_TenorPeriod.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GWR490_GWRCollectionDraftA_TenorPeriod">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="D"/>
 *     &lt;enumeration value="M"/>
 *     &lt;enumeration value="Q"/>
 *     &lt;enumeration value="W"/>
 *     &lt;enumeration value="Y"/>
 *     &lt;minLength value="1"/>
 *     &lt;maxLength value="1"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "GWR490_GWRCollectionDraftA_TenorPeriod")
@XmlEnum
public enum GWR490GWRCollectionDraftATenorPeriod {

    D,
    M,
    Q,
    W,
    Y;

    public String value() {
        return name();
    }

    public static GWR490GWRCollectionDraftATenorPeriod fromValue(String v) {
        return valueOf(v);
    }

}
