//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.messages;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.misys.tiplus2.apps.ti.service.common.EnigmaBoolean;
import com.misys.tiplus2.apps.ti.service.common.GWRCounterGuaranteeIdentifier;
import com.misys.tiplus2.apps.ti.service.common.GWRGuaranteeDetails;
import com.misys.tiplus2.apps.ti.service.common.GWRMoney;
import com.misys.tiplus2.apps.ti.service.common.GWRParty;


/**
 * <p>Java class for GWR700G complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GWR700G">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:messages.service.ti.apps.tiplus2.misys.com}GWR700GS">
 *       &lt;sequence>
 *         &lt;element name="GuaranteeDetails" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRGuaranteeDetails" minOccurs="0"/>
 *         &lt;element name="CounterGuaranteeAmount" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRMoney" minOccurs="0"/>
 *         &lt;element name="CounterGuaranteeExpiryDate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDate" minOccurs="0"/>
 *         &lt;element name="CounterGuaranteeIssBank" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRParty" minOccurs="0"/>
 *         &lt;element name="CounterGuaranteePrincipalBank" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRParty" minOccurs="0"/>
 *         &lt;element name="CustomerCounter" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRBool" minOccurs="0"/>
 *         &lt;element name="CustomerCounterExpiryDate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDate" minOccurs="0"/>
 *         &lt;element name="ShipmentAdditionalInformation" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRText6x35" minOccurs="0"/>
 *         &lt;element name="BillNumber" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRBillNumber" minOccurs="0"/>
 *         &lt;element name="FlightDetails" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRFlightDetails" minOccurs="0"/>
 *         &lt;element name="LetterOfIndemnity" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRBool" minOccurs="0"/>
 *         &lt;element name="ShippingCompany" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRShippingCompany" minOccurs="0"/>
 *         &lt;element name="VesselName" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRShipmentVessel" minOccurs="0"/>
 *         &lt;element name="CounterGteeIdentifier" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRCounterGuaranteeIdentifier" minOccurs="0"/>
 *         &lt;element name="FreeFormatInstructionsForSWIFT" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRText400x65" minOccurs="0"/>
 *         &lt;element name="ContractReference" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRReference" minOccurs="0"/>
 *         &lt;element name="ContractDate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDate" minOccurs="0"/>
 *         &lt;element name="ContractCurrency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContractAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContractPercent" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRPercentAmount" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GWR700G", propOrder = {
    "guaranteeDetails",
    "counterGuaranteeAmount",
    "counterGuaranteeExpiryDate",
    "counterGuaranteeIssBank",
    "counterGuaranteePrincipalBank",
    "customerCounter",
    "customerCounterExpiryDate",
    "shipmentAdditionalInformation",
    "billNumber",
    "flightDetails",
    "letterOfIndemnity",
    "shippingCompany",
    "vesselName",
    "counterGteeIdentifier",
    "freeFormatInstructionsForSWIFT",
    "contractReference",
    "contractDate",
    "contractCurrency",
    "contractAmount",
    "contractPercent"
})
@XmlSeeAlso({
    GWR700GT.class,
    GWR700GP.class
})
public class GWR700G
    extends GWR700GS
{

    @XmlElement(name = "GuaranteeDetails")
    protected GWRGuaranteeDetails guaranteeDetails;
    @XmlElement(name = "CounterGuaranteeAmount")
    protected GWRMoney counterGuaranteeAmount;
    @XmlElementRef(name = "CounterGuaranteeExpiryDate", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> counterGuaranteeExpiryDate;
    @XmlElement(name = "CounterGuaranteeIssBank")
    protected GWRParty counterGuaranteeIssBank;
    @XmlElement(name = "CounterGuaranteePrincipalBank")
    protected GWRParty counterGuaranteePrincipalBank;
    @XmlElement(name = "CustomerCounter")
    protected EnigmaBoolean customerCounter;
    @XmlElementRef(name = "CustomerCounterExpiryDate", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> customerCounterExpiryDate;
    @XmlElement(name = "ShipmentAdditionalInformation")
    protected String shipmentAdditionalInformation;
    @XmlElement(name = "BillNumber")
    protected String billNumber;
    @XmlElementRef(name = "FlightDetails", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<String> flightDetails;
    @XmlElement(name = "LetterOfIndemnity")
    protected EnigmaBoolean letterOfIndemnity;
    @XmlElementRef(name = "ShippingCompany", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<String> shippingCompany;
    @XmlElement(name = "VesselName")
    protected String vesselName;
    @XmlElementRef(name = "CounterGteeIdentifier", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<GWRCounterGuaranteeIdentifier> counterGteeIdentifier;
    @XmlElement(name = "FreeFormatInstructionsForSWIFT")
    protected String freeFormatInstructionsForSWIFT;
    @XmlElement(name = "ContractReference")
    protected String contractReference;
    @XmlElementRef(name = "ContractDate", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> contractDate;
    @XmlElement(name = "ContractCurrency")
    protected String contractCurrency;
    @XmlElement(name = "ContractAmount")
    protected String contractAmount;
    @XmlElement(name = "ContractPercent")
    protected BigDecimal contractPercent;

    /**
     * Gets the value of the guaranteeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link GWRGuaranteeDetails }
     *     
     */
    public GWRGuaranteeDetails getGuaranteeDetails() {
        return guaranteeDetails;
    }

    /**
     * Sets the value of the guaranteeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRGuaranteeDetails }
     *     
     */
    public void setGuaranteeDetails(GWRGuaranteeDetails value) {
        this.guaranteeDetails = value;
    }

    /**
     * Gets the value of the counterGuaranteeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link GWRMoney }
     *     
     */
    public GWRMoney getCounterGuaranteeAmount() {
        return counterGuaranteeAmount;
    }

    /**
     * Sets the value of the counterGuaranteeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRMoney }
     *     
     */
    public void setCounterGuaranteeAmount(GWRMoney value) {
        this.counterGuaranteeAmount = value;
    }

    /**
     * Gets the value of the counterGuaranteeExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getCounterGuaranteeExpiryDate() {
        return counterGuaranteeExpiryDate;
    }

    /**
     * Sets the value of the counterGuaranteeExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setCounterGuaranteeExpiryDate(JAXBElement<XMLGregorianCalendar> value) {
        this.counterGuaranteeExpiryDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the counterGuaranteeIssBank property.
     * 
     * @return
     *     possible object is
     *     {@link GWRParty }
     *     
     */
    public GWRParty getCounterGuaranteeIssBank() {
        return counterGuaranteeIssBank;
    }

    /**
     * Sets the value of the counterGuaranteeIssBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRParty }
     *     
     */
    public void setCounterGuaranteeIssBank(GWRParty value) {
        this.counterGuaranteeIssBank = value;
    }

    /**
     * Gets the value of the counterGuaranteePrincipalBank property.
     * 
     * @return
     *     possible object is
     *     {@link GWRParty }
     *     
     */
    public GWRParty getCounterGuaranteePrincipalBank() {
        return counterGuaranteePrincipalBank;
    }

    /**
     * Sets the value of the counterGuaranteePrincipalBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRParty }
     *     
     */
    public void setCounterGuaranteePrincipalBank(GWRParty value) {
        this.counterGuaranteePrincipalBank = value;
    }

    /**
     * Gets the value of the customerCounter property.
     * 
     * @return
     *     possible object is
     *     {@link EnigmaBoolean }
     *     
     */
    public EnigmaBoolean getCustomerCounter() {
        return customerCounter;
    }

    /**
     * Sets the value of the customerCounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnigmaBoolean }
     *     
     */
    public void setCustomerCounter(EnigmaBoolean value) {
        this.customerCounter = value;
    }

    /**
     * Gets the value of the customerCounterExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getCustomerCounterExpiryDate() {
        return customerCounterExpiryDate;
    }

    /**
     * Sets the value of the customerCounterExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setCustomerCounterExpiryDate(JAXBElement<XMLGregorianCalendar> value) {
        this.customerCounterExpiryDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the shipmentAdditionalInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentAdditionalInformation() {
        return shipmentAdditionalInformation;
    }

    /**
     * Sets the value of the shipmentAdditionalInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentAdditionalInformation(String value) {
        this.shipmentAdditionalInformation = value;
    }

    /**
     * Gets the value of the billNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillNumber() {
        return billNumber;
    }

    /**
     * Sets the value of the billNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillNumber(String value) {
        this.billNumber = value;
    }

    /**
     * Gets the value of the flightDetails property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFlightDetails() {
        return flightDetails;
    }

    /**
     * Sets the value of the flightDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFlightDetails(JAXBElement<String> value) {
        this.flightDetails = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the letterOfIndemnity property.
     * 
     * @return
     *     possible object is
     *     {@link EnigmaBoolean }
     *     
     */
    public EnigmaBoolean getLetterOfIndemnity() {
        return letterOfIndemnity;
    }

    /**
     * Sets the value of the letterOfIndemnity property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnigmaBoolean }
     *     
     */
    public void setLetterOfIndemnity(EnigmaBoolean value) {
        this.letterOfIndemnity = value;
    }

    /**
     * Gets the value of the shippingCompany property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getShippingCompany() {
        return shippingCompany;
    }

    /**
     * Sets the value of the shippingCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setShippingCompany(JAXBElement<String> value) {
        this.shippingCompany = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the vesselName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVesselName() {
        return vesselName;
    }

    /**
     * Sets the value of the vesselName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselName(String value) {
        this.vesselName = value;
    }

    /**
     * Gets the value of the counterGteeIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GWRCounterGuaranteeIdentifier }{@code >}
     *     
     */
    public JAXBElement<GWRCounterGuaranteeIdentifier> getCounterGteeIdentifier() {
        return counterGteeIdentifier;
    }

    /**
     * Sets the value of the counterGteeIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GWRCounterGuaranteeIdentifier }{@code >}
     *     
     */
    public void setCounterGteeIdentifier(JAXBElement<GWRCounterGuaranteeIdentifier> value) {
        this.counterGteeIdentifier = ((JAXBElement<GWRCounterGuaranteeIdentifier> ) value);
    }

    /**
     * Gets the value of the freeFormatInstructionsForSWIFT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeFormatInstructionsForSWIFT() {
        return freeFormatInstructionsForSWIFT;
    }

    /**
     * Sets the value of the freeFormatInstructionsForSWIFT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeFormatInstructionsForSWIFT(String value) {
        this.freeFormatInstructionsForSWIFT = value;
    }

    /**
     * Gets the value of the contractReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractReference() {
        return contractReference;
    }

    /**
     * Sets the value of the contractReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractReference(String value) {
        this.contractReference = value;
    }

    /**
     * Gets the value of the contractDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getContractDate() {
        return contractDate;
    }

    /**
     * Sets the value of the contractDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setContractDate(JAXBElement<XMLGregorianCalendar> value) {
        this.contractDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the contractCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractCurrency() {
        return contractCurrency;
    }

    /**
     * Sets the value of the contractCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractCurrency(String value) {
        this.contractCurrency = value;
    }

    /**
     * Gets the value of the contractAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractAmount() {
        return contractAmount;
    }

    /**
     * Sets the value of the contractAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractAmount(String value) {
        this.contractAmount = value;
    }

    /**
     * Gets the value of the contractPercent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getContractPercent() {
        return contractPercent;
    }

    /**
     * Sets the value of the contractPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setContractPercent(BigDecimal value) {
        this.contractPercent = value;
    }

}
