//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import com.misys.tiplus2.apps.ti.service.common.EnigmaBoolean;
import com.misys.tiplus2.apps.ti.service.common.GWRAdditionalPartiesToAmend;
import com.misys.tiplus2.apps.ti.service.common.GWRMoney;
import com.misys.tiplus2.apps.ti.service.common.GWRParty;


/**
 * .
 * 
 * <p>Java class for GWR707 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GWR707">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:messages.service.ti.apps.tiplus2.misys.com}GWRILC">
 *       &lt;sequence>
 *         &lt;element name="Sender" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRParty" minOccurs="0"/>
 *         &lt;element name="BenApprovalReq" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRBool" minOccurs="0"/>
 *         &lt;element name="IncreaseAmount" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRMoney" minOccurs="0"/>
 *         &lt;element name="DecreaseAmount" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRMoney" minOccurs="0"/>
 *         &lt;element name="AmendmentNarrative" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRText35x50" minOccurs="0"/>
 *         &lt;element name="AmendChanges" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRText35x50" minOccurs="0"/>
 *         &lt;element name="ProductType" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRBranchProductType" minOccurs="0"/>
 *         &lt;element name="AdditionalParties" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAdditionalPartiesToAmend" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GWR707", propOrder = {
    "sender",
    "benApprovalReq",
    "increaseAmount",
    "decreaseAmount",
    "amendmentNarrative",
    "amendChanges",
    "productType",
    "additionalParties"
})
@XmlSeeAlso({
    TFILCAMN.class,
    GWR707SN.class
})
public class GWR707
    extends GWRILC
{

    @XmlElement(name = "Sender")
    protected GWRParty sender;
    @XmlElement(name = "BenApprovalReq")
    protected EnigmaBoolean benApprovalReq;
    @XmlElement(name = "IncreaseAmount")
    protected GWRMoney increaseAmount;
    @XmlElement(name = "DecreaseAmount")
    protected GWRMoney decreaseAmount;
    @XmlElement(name = "AmendmentNarrative")
    protected String amendmentNarrative;
    @XmlElement(name = "AmendChanges")
    protected String amendChanges;
    @XmlElement(name = "ProductType")
    protected String productType;
    @XmlElement(name = "AdditionalParties")
    protected GWRAdditionalPartiesToAmend additionalParties;

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link GWRParty }
     *     
     */
    public GWRParty getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRParty }
     *     
     */
    public void setSender(GWRParty value) {
        this.sender = value;
    }

    /**
     * Gets the value of the benApprovalReq property.
     * 
     * @return
     *     possible object is
     *     {@link EnigmaBoolean }
     *     
     */
    public EnigmaBoolean getBenApprovalReq() {
        return benApprovalReq;
    }

    /**
     * Sets the value of the benApprovalReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnigmaBoolean }
     *     
     */
    public void setBenApprovalReq(EnigmaBoolean value) {
        this.benApprovalReq = value;
    }

    /**
     * Gets the value of the increaseAmount property.
     * 
     * @return
     *     possible object is
     *     {@link GWRMoney }
     *     
     */
    public GWRMoney getIncreaseAmount() {
        return increaseAmount;
    }

    /**
     * Sets the value of the increaseAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRMoney }
     *     
     */
    public void setIncreaseAmount(GWRMoney value) {
        this.increaseAmount = value;
    }

    /**
     * Gets the value of the decreaseAmount property.
     * 
     * @return
     *     possible object is
     *     {@link GWRMoney }
     *     
     */
    public GWRMoney getDecreaseAmount() {
        return decreaseAmount;
    }

    /**
     * Sets the value of the decreaseAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRMoney }
     *     
     */
    public void setDecreaseAmount(GWRMoney value) {
        this.decreaseAmount = value;
    }

    /**
     * Gets the value of the amendmentNarrative property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmendmentNarrative() {
        return amendmentNarrative;
    }

    /**
     * Sets the value of the amendmentNarrative property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmendmentNarrative(String value) {
        this.amendmentNarrative = value;
    }

    /**
     * Gets the value of the amendChanges property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmendChanges() {
        return amendChanges;
    }

    /**
     * Sets the value of the amendChanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmendChanges(String value) {
        this.amendChanges = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductType(String value) {
        this.productType = value;
    }

    /**
     * Gets the value of the additionalParties property.
     * 
     * @return
     *     possible object is
     *     {@link GWRAdditionalPartiesToAmend }
     *     
     */
    public GWRAdditionalPartiesToAmend getAdditionalParties() {
        return additionalParties;
    }

    /**
     * Sets the value of the additionalParties property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRAdditionalPartiesToAmend }
     *     
     */
    public void setAdditionalParties(GWRAdditionalPartiesToAmend value) {
        this.additionalParties = value;
    }

}
