//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * .
 * 
 * <p>Java class for GWRFDRD complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GWRFDRD">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:messages.service.ti.apps.tiplus2.misys.com}GatewayRFactoring">
 *       &lt;sequence>
 *         &lt;element name="InstructionsReceived" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRText10x50" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GWRFDRD", propOrder = {
    "instructionsReceived"
})
@XmlSeeAlso({
    TFFACDRD.class
})
public class GWRFDRD
    extends GatewayRFactoring
{

    @XmlElement(name = "InstructionsReceived")
    protected String instructionsReceived;

    /**
     * Gets the value of the instructionsReceived property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstructionsReceived() {
        return instructionsReceived;
    }

    /**
     * Sets the value of the instructionsReceived property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstructionsReceived(String value) {
        this.instructionsReceived = value;
    }

}
