//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * class' implementation. and removed.
 * 
 * <p>Java class for GWRReceiveDocuments complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GWRReceiveDocuments">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:messages.service.ti.apps.tiplus2.misys.com}GatewayEventR">
 *       &lt;sequence>
 *         &lt;element name="Narrative" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRTextUnrestricted" minOccurs="0"/>
 *         &lt;element name="EventFurtherID" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWREventFurtherID" minOccurs="0"/>
 *         &lt;element name="ExtraInformation" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRExtraInformation" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GWRReceiveDocuments", propOrder = {
    "narrative",
    "eventFurtherID",
    "extraInformation"
})
@XmlSeeAlso({
    TFRCVDOC.class
})
public class GWRReceiveDocuments
    extends GatewayEventR
{

    @XmlElement(name = "Narrative")
    protected String narrative;
    @XmlElement(name = "EventFurtherID")
    protected String eventFurtherID;
    @XmlElement(name = "ExtraInformation")
    protected String extraInformation;

    /**
     * Gets the value of the narrative property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNarrative() {
        return narrative;
    }

    /**
     * Sets the value of the narrative property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNarrative(String value) {
        this.narrative = value;
    }

    /**
     * Gets the value of the eventFurtherID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventFurtherID() {
        return eventFurtherID;
    }

    /**
     * Sets the value of the eventFurtherID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventFurtherID(String value) {
        this.eventFurtherID = value;
    }

    /**
     * Gets the value of the extraInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtraInformation() {
        return extraInformation;
    }

    /**
     * Sets the value of the extraInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtraInformation(String value) {
        this.extraInformation = value;
    }

}
