//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.messages;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.misys.tiplus2.apps.ti.service.common.EnigmaBoolean;
import com.misys.tiplus2.apps.ti.service.common.GWRAdditionalParties;
import com.misys.tiplus2.apps.ti.service.common.GWRMarginDeposit;
import com.misys.tiplus2.apps.ti.service.common.GWRMoney;
import com.misys.tiplus2.apps.ti.service.common.GWRParty;
import com.misys.tiplus2.apps.ti.service.common.GWRSpecialFields;


/**
 * GatewayEventR.CreateOrGetMasterForFullDefiningMessage() and removed.
 * 
 * <p>Java class for GWRSHGAPP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GWRSHGAPP">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:messages.service.ti.apps.tiplus2.misys.com}GatewayEventR">
 *       &lt;sequence>
 *         &lt;element name="ApplicationDate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDate" minOccurs="0"/>
 *         &lt;element name="IssueDate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDate" minOccurs="0"/>
 *         &lt;element name="ExpiryDate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDate" minOccurs="0"/>
 *         &lt;element name="MultipleDocs" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRBool" minOccurs="0"/>
 *         &lt;element name="AdviceMethod" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRTransferMethodAdviceFormat" minOccurs="0"/>
 *         &lt;element name="Importer" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRParty" minOccurs="0"/>
 *         &lt;element name="ShippingParty" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRParty" minOccurs="0"/>
 *         &lt;element name="GuaranteeAmount" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRMoney" minOccurs="0"/>
 *         &lt;element name="OriginatingTransaction" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRReference" minOccurs="0"/>
 *         &lt;element name="DocumentOfTitles" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DocumentOfTitle" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="DoTType" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="3"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="DoTShipAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DoTShipCcy" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="3"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="DoTReference" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="20"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="DoTField1" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="222"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="DoTField2" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="222"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="DoTField3" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="222"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="DoTField4" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="222"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="DoTField5" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="222"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="DoTField6" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="222"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="DoTField7" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="222"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="DoTField8" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="222"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="DoTField9" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="222"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="DoTField110" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="222"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AdditionalConditions" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRText10000" minOccurs="0"/>
 *         &lt;element name="NotesToConsignee" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRText10000" minOccurs="0"/>
 *         &lt;element name="NotesToShippingCo" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRText10000" minOccurs="0"/>
 *         &lt;element name="eBankMasterRef" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWREBankReference" minOccurs="0"/>
 *         &lt;element name="eBankEventRef" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWREBankReference" minOccurs="0"/>
 *         &lt;element name="SpecialFields" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRSpecialFields" minOccurs="0"/>
 *         &lt;element name="PrincipalAccountNumber" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAccountKey" minOccurs="0"/>
 *         &lt;element name="FeeAccountNumber" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAccountKey" minOccurs="0"/>
 *         &lt;element name="ChargeAccount" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRBenAccountID" minOccurs="0"/>
 *         &lt;element name="PrincipalAccount" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRBenAccountID" minOccurs="0"/>
 *         &lt;element name="AdditionalParties" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAdditionalParties" minOccurs="0"/>
 *         &lt;element name="MarginDeposit" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRMarginDeposit" minOccurs="0"/>
 *         &lt;element name="Collateral" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CollateralDetail" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Code" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="8"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Description" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="25"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Amount" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *                                   &lt;fractionDigits value="0"/>
 *                                   &lt;totalDigits value="15"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Currency" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="3"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="OtherDetailsType" type="{urn:messages.service.ti.apps.tiplus2.misys.com}GWRSHGAPP_Collaterals_OtherDetailsType" minOccurs="0"/>
 *                             &lt;element name="CustomerDDA" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="25"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="OtherPledge" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="50"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Surety" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="50"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GWRSHGAPP", propOrder = {
    "applicationDate",
    "issueDate",
    "expiryDate",
    "multipleDocs",
    "adviceMethod",
    "importer",
    "shippingParty",
    "guaranteeAmount",
    "originatingTransaction",
    "documentOfTitles",
    "additionalConditions",
    "notesToConsignee",
    "notesToShippingCo",
    "eBankMasterRef",
    "eBankEventRef",
    "specialFields",
    "principalAccountNumber",
    "feeAccountNumber",
    "chargeAccount",
    "principalAccount",
    "additionalParties",
    "marginDeposit",
    "collateral"
})
@XmlSeeAlso({
    TFSHGAPP.class
})
public class GWRSHGAPP
    extends GatewayEventR
{

    @XmlElementRef(name = "ApplicationDate", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> applicationDate;
    @XmlElementRef(name = "IssueDate", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> issueDate;
    @XmlElementRef(name = "ExpiryDate", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> expiryDate;
    @XmlElement(name = "MultipleDocs")
    protected EnigmaBoolean multipleDocs;
    @XmlElement(name = "AdviceMethod")
    protected String adviceMethod;
    @XmlElement(name = "Importer")
    protected GWRParty importer;
    @XmlElement(name = "ShippingParty")
    protected GWRParty shippingParty;
    @XmlElement(name = "GuaranteeAmount")
    protected GWRMoney guaranteeAmount;
    @XmlElement(name = "OriginatingTransaction")
    protected String originatingTransaction;
    @XmlElement(name = "DocumentOfTitles")
    protected GWRSHGAPP.DocumentOfTitles documentOfTitles;
    @XmlElement(name = "AdditionalConditions")
    protected String additionalConditions;
    @XmlElement(name = "NotesToConsignee")
    protected String notesToConsignee;
    @XmlElement(name = "NotesToShippingCo")
    protected String notesToShippingCo;
    protected String eBankMasterRef;
    protected String eBankEventRef;
    @XmlElement(name = "SpecialFields")
    protected GWRSpecialFields specialFields;
    @XmlElement(name = "PrincipalAccountNumber")
    protected String principalAccountNumber;
    @XmlElement(name = "FeeAccountNumber")
    protected String feeAccountNumber;
    @XmlElementRef(name = "ChargeAccount", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<String> chargeAccount;
    @XmlElementRef(name = "PrincipalAccount", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<String> principalAccount;
    @XmlElement(name = "AdditionalParties")
    protected GWRAdditionalParties additionalParties;
    @XmlElement(name = "MarginDeposit")
    protected GWRMarginDeposit marginDeposit;
    @XmlElement(name = "Collateral")
    protected GWRSHGAPP.Collateral collateral;

    /**
     * Gets the value of the applicationDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getApplicationDate() {
        return applicationDate;
    }

    /**
     * Sets the value of the applicationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setApplicationDate(JAXBElement<XMLGregorianCalendar> value) {
        this.applicationDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the issueDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setIssueDate(JAXBElement<XMLGregorianCalendar> value) {
        this.issueDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setExpiryDate(JAXBElement<XMLGregorianCalendar> value) {
        this.expiryDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the multipleDocs property.
     * 
     * @return
     *     possible object is
     *     {@link EnigmaBoolean }
     *     
     */
    public EnigmaBoolean getMultipleDocs() {
        return multipleDocs;
    }

    /**
     * Sets the value of the multipleDocs property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnigmaBoolean }
     *     
     */
    public void setMultipleDocs(EnigmaBoolean value) {
        this.multipleDocs = value;
    }

    /**
     * Gets the value of the adviceMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdviceMethod() {
        return adviceMethod;
    }

    /**
     * Sets the value of the adviceMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdviceMethod(String value) {
        this.adviceMethod = value;
    }

    /**
     * Gets the value of the importer property.
     * 
     * @return
     *     possible object is
     *     {@link GWRParty }
     *     
     */
    public GWRParty getImporter() {
        return importer;
    }

    /**
     * Sets the value of the importer property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRParty }
     *     
     */
    public void setImporter(GWRParty value) {
        this.importer = value;
    }

    /**
     * Gets the value of the shippingParty property.
     * 
     * @return
     *     possible object is
     *     {@link GWRParty }
     *     
     */
    public GWRParty getShippingParty() {
        return shippingParty;
    }

    /**
     * Sets the value of the shippingParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRParty }
     *     
     */
    public void setShippingParty(GWRParty value) {
        this.shippingParty = value;
    }

    /**
     * Gets the value of the guaranteeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link GWRMoney }
     *     
     */
    public GWRMoney getGuaranteeAmount() {
        return guaranteeAmount;
    }

    /**
     * Sets the value of the guaranteeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRMoney }
     *     
     */
    public void setGuaranteeAmount(GWRMoney value) {
        this.guaranteeAmount = value;
    }

    /**
     * Gets the value of the originatingTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginatingTransaction() {
        return originatingTransaction;
    }

    /**
     * Sets the value of the originatingTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginatingTransaction(String value) {
        this.originatingTransaction = value;
    }

    /**
     * Gets the value of the documentOfTitles property.
     * 
     * @return
     *     possible object is
     *     {@link GWRSHGAPP.DocumentOfTitles }
     *     
     */
    public GWRSHGAPP.DocumentOfTitles getDocumentOfTitles() {
        return documentOfTitles;
    }

    /**
     * Sets the value of the documentOfTitles property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRSHGAPP.DocumentOfTitles }
     *     
     */
    public void setDocumentOfTitles(GWRSHGAPP.DocumentOfTitles value) {
        this.documentOfTitles = value;
    }

    /**
     * Gets the value of the additionalConditions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalConditions() {
        return additionalConditions;
    }

    /**
     * Sets the value of the additionalConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalConditions(String value) {
        this.additionalConditions = value;
    }

    /**
     * Gets the value of the notesToConsignee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotesToConsignee() {
        return notesToConsignee;
    }

    /**
     * Sets the value of the notesToConsignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotesToConsignee(String value) {
        this.notesToConsignee = value;
    }

    /**
     * Gets the value of the notesToShippingCo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotesToShippingCo() {
        return notesToShippingCo;
    }

    /**
     * Sets the value of the notesToShippingCo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotesToShippingCo(String value) {
        this.notesToShippingCo = value;
    }

    /**
     * Gets the value of the eBankMasterRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEBankMasterRef() {
        return eBankMasterRef;
    }

    /**
     * Sets the value of the eBankMasterRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEBankMasterRef(String value) {
        this.eBankMasterRef = value;
    }

    /**
     * Gets the value of the eBankEventRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEBankEventRef() {
        return eBankEventRef;
    }

    /**
     * Sets the value of the eBankEventRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEBankEventRef(String value) {
        this.eBankEventRef = value;
    }

    /**
     * Gets the value of the specialFields property.
     * 
     * @return
     *     possible object is
     *     {@link GWRSpecialFields }
     *     
     */
    public GWRSpecialFields getSpecialFields() {
        return specialFields;
    }

    /**
     * Sets the value of the specialFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRSpecialFields }
     *     
     */
    public void setSpecialFields(GWRSpecialFields value) {
        this.specialFields = value;
    }

    /**
     * Gets the value of the principalAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrincipalAccountNumber() {
        return principalAccountNumber;
    }

    /**
     * Sets the value of the principalAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrincipalAccountNumber(String value) {
        this.principalAccountNumber = value;
    }

    /**
     * Gets the value of the feeAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeeAccountNumber() {
        return feeAccountNumber;
    }

    /**
     * Sets the value of the feeAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeeAccountNumber(String value) {
        this.feeAccountNumber = value;
    }

    /**
     * Gets the value of the chargeAccount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getChargeAccount() {
        return chargeAccount;
    }

    /**
     * Sets the value of the chargeAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setChargeAccount(JAXBElement<String> value) {
        this.chargeAccount = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the principalAccount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPrincipalAccount() {
        return principalAccount;
    }

    /**
     * Sets the value of the principalAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPrincipalAccount(JAXBElement<String> value) {
        this.principalAccount = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the additionalParties property.
     * 
     * @return
     *     possible object is
     *     {@link GWRAdditionalParties }
     *     
     */
    public GWRAdditionalParties getAdditionalParties() {
        return additionalParties;
    }

    /**
     * Sets the value of the additionalParties property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRAdditionalParties }
     *     
     */
    public void setAdditionalParties(GWRAdditionalParties value) {
        this.additionalParties = value;
    }

    /**
     * Gets the value of the marginDeposit property.
     * 
     * @return
     *     possible object is
     *     {@link GWRMarginDeposit }
     *     
     */
    public GWRMarginDeposit getMarginDeposit() {
        return marginDeposit;
    }

    /**
     * Sets the value of the marginDeposit property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRMarginDeposit }
     *     
     */
    public void setMarginDeposit(GWRMarginDeposit value) {
        this.marginDeposit = value;
    }

    /**
     * Gets the value of the collateral property.
     * 
     * @return
     *     possible object is
     *     {@link GWRSHGAPP.Collateral }
     *     
     */
    public GWRSHGAPP.Collateral getCollateral() {
        return collateral;
    }

    /**
     * Sets the value of the collateral property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRSHGAPP.Collateral }
     *     
     */
    public void setCollateral(GWRSHGAPP.Collateral value) {
        this.collateral = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CollateralDetail" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Code" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="8"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Description" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="25"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Amount" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
     *                         &lt;fractionDigits value="0"/>
     *                         &lt;totalDigits value="15"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Currency" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="3"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="OtherDetailsType" type="{urn:messages.service.ti.apps.tiplus2.misys.com}GWRSHGAPP_Collaterals_OtherDetailsType" minOccurs="0"/>
     *                   &lt;element name="CustomerDDA" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="25"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="OtherPledge" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="50"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Surety" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="50"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "collateralDetail"
    })
    public static class Collateral {

        @XmlElement(name = "CollateralDetail", required = true)
        protected List<GWRSHGAPP.Collateral.CollateralDetail> collateralDetail;

        /**
         * Gets the value of the collateralDetail property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the collateralDetail property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCollateralDetail().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GWRSHGAPP.Collateral.CollateralDetail }
         * 
         * 
         */
        public List<GWRSHGAPP.Collateral.CollateralDetail> getCollateralDetail() {
            if (collateralDetail == null) {
                collateralDetail = new ArrayList<GWRSHGAPP.Collateral.CollateralDetail>();
            }
            return this.collateralDetail;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Code" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="8"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Description" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="25"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Amount" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
         *               &lt;fractionDigits value="0"/>
         *               &lt;totalDigits value="15"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Currency" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="3"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="OtherDetailsType" type="{urn:messages.service.ti.apps.tiplus2.misys.com}GWRSHGAPP_Collaterals_OtherDetailsType" minOccurs="0"/>
         *         &lt;element name="CustomerDDA" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="25"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="OtherPledge" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="50"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Surety" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="50"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "code",
            "description",
            "amount",
            "currency",
            "otherDetailsType",
            "customerDDA",
            "otherPledge",
            "surety"
        })
        public static class CollateralDetail {

            @XmlElementRef(name = "Code", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
            protected JAXBElement<String> code;
            @XmlElement(name = "Description")
            protected String description;
            @XmlElementRef(name = "Amount", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
            protected JAXBElement<Long> amount;
            @XmlElementRef(name = "Currency", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
            protected JAXBElement<String> currency;
            @XmlElement(name = "OtherDetailsType")
            protected GWRSHGAPPCollateralsOtherDetailsType otherDetailsType;
            @XmlElement(name = "CustomerDDA")
            protected String customerDDA;
            @XmlElement(name = "OtherPledge")
            protected String otherPledge;
            @XmlElement(name = "Surety")
            protected String surety;

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link JAXBElement }{@code <}{@link String }{@code >}
             *     
             */
            public JAXBElement<String> getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link JAXBElement }{@code <}{@link String }{@code >}
             *     
             */
            public void setCode(JAXBElement<String> value) {
                this.code = ((JAXBElement<String> ) value);
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the amount property.
             * 
             * @return
             *     possible object is
             *     {@link JAXBElement }{@code <}{@link Long }{@code >}
             *     
             */
            public JAXBElement<Long> getAmount() {
                return amount;
            }

            /**
             * Sets the value of the amount property.
             * 
             * @param value
             *     allowed object is
             *     {@link JAXBElement }{@code <}{@link Long }{@code >}
             *     
             */
            public void setAmount(JAXBElement<Long> value) {
                this.amount = ((JAXBElement<Long> ) value);
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return
             *     possible object is
             *     {@link JAXBElement }{@code <}{@link String }{@code >}
             *     
             */
            public JAXBElement<String> getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *     allowed object is
             *     {@link JAXBElement }{@code <}{@link String }{@code >}
             *     
             */
            public void setCurrency(JAXBElement<String> value) {
                this.currency = ((JAXBElement<String> ) value);
            }

            /**
             * Gets the value of the otherDetailsType property.
             * 
             * @return
             *     possible object is
             *     {@link GWRSHGAPPCollateralsOtherDetailsType }
             *     
             */
            public GWRSHGAPPCollateralsOtherDetailsType getOtherDetailsType() {
                return otherDetailsType;
            }

            /**
             * Sets the value of the otherDetailsType property.
             * 
             * @param value
             *     allowed object is
             *     {@link GWRSHGAPPCollateralsOtherDetailsType }
             *     
             */
            public void setOtherDetailsType(GWRSHGAPPCollateralsOtherDetailsType value) {
                this.otherDetailsType = value;
            }

            /**
             * Gets the value of the customerDDA property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCustomerDDA() {
                return customerDDA;
            }

            /**
             * Sets the value of the customerDDA property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCustomerDDA(String value) {
                this.customerDDA = value;
            }

            /**
             * Gets the value of the otherPledge property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOtherPledge() {
                return otherPledge;
            }

            /**
             * Sets the value of the otherPledge property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOtherPledge(String value) {
                this.otherPledge = value;
            }

            /**
             * Gets the value of the surety property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSurety() {
                return surety;
            }

            /**
             * Sets the value of the surety property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSurety(String value) {
                this.surety = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DocumentOfTitle" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="DoTType" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="3"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="DoTShipAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DoTShipCcy" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="3"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="DoTReference" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="20"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="DoTField1" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="222"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="DoTField2" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="222"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="DoTField3" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="222"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="DoTField4" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="222"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="DoTField5" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="222"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="DoTField6" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="222"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="DoTField7" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="222"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="DoTField8" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="222"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="DoTField9" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="222"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="DoTField110" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="222"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "documentOfTitle"
    })
    public static class DocumentOfTitles {

        @XmlElement(name = "DocumentOfTitle", required = true)
        protected List<GWRSHGAPP.DocumentOfTitles.DocumentOfTitle> documentOfTitle;

        /**
         * Gets the value of the documentOfTitle property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the documentOfTitle property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDocumentOfTitle().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GWRSHGAPP.DocumentOfTitles.DocumentOfTitle }
         * 
         * 
         */
        public List<GWRSHGAPP.DocumentOfTitles.DocumentOfTitle> getDocumentOfTitle() {
            if (documentOfTitle == null) {
                documentOfTitle = new ArrayList<GWRSHGAPP.DocumentOfTitles.DocumentOfTitle>();
            }
            return this.documentOfTitle;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="DoTType" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="3"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="DoTShipAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DoTShipCcy" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="3"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="DoTReference" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="20"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="DoTField1" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="222"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="DoTField2" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="222"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="DoTField3" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="222"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="DoTField4" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="222"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="DoTField5" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="222"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="DoTField6" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="222"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="DoTField7" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="222"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="DoTField8" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="222"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="DoTField9" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="222"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="DoTField110" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="222"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "doTType",
            "doTShipAmt",
            "doTShipCcy",
            "doTReference",
            "doTField1",
            "doTField2",
            "doTField3",
            "doTField4",
            "doTField5",
            "doTField6",
            "doTField7",
            "doTField8",
            "doTField9",
            "doTField110"
        })
        public static class DocumentOfTitle {

            @XmlElement(name = "DoTType")
            protected String doTType;
            @XmlElement(name = "DoTShipAmt")
            protected String doTShipAmt;
            @XmlElement(name = "DoTShipCcy")
            protected String doTShipCcy;
            @XmlElementRef(name = "DoTReference", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
            protected JAXBElement<String> doTReference;
            @XmlElement(name = "DoTField1")
            protected String doTField1;
            @XmlElement(name = "DoTField2")
            protected String doTField2;
            @XmlElement(name = "DoTField3")
            protected String doTField3;
            @XmlElement(name = "DoTField4")
            protected String doTField4;
            @XmlElement(name = "DoTField5")
            protected String doTField5;
            @XmlElement(name = "DoTField6")
            protected String doTField6;
            @XmlElement(name = "DoTField7")
            protected String doTField7;
            @XmlElement(name = "DoTField8")
            protected String doTField8;
            @XmlElement(name = "DoTField9")
            protected String doTField9;
            @XmlElement(name = "DoTField110")
            protected String doTField110;

            /**
             * Gets the value of the doTType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDoTType() {
                return doTType;
            }

            /**
             * Sets the value of the doTType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDoTType(String value) {
                this.doTType = value;
            }

            /**
             * Gets the value of the doTShipAmt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDoTShipAmt() {
                return doTShipAmt;
            }

            /**
             * Sets the value of the doTShipAmt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDoTShipAmt(String value) {
                this.doTShipAmt = value;
            }

            /**
             * Gets the value of the doTShipCcy property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDoTShipCcy() {
                return doTShipCcy;
            }

            /**
             * Sets the value of the doTShipCcy property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDoTShipCcy(String value) {
                this.doTShipCcy = value;
            }

            /**
             * Gets the value of the doTReference property.
             * 
             * @return
             *     possible object is
             *     {@link JAXBElement }{@code <}{@link String }{@code >}
             *     
             */
            public JAXBElement<String> getDoTReference() {
                return doTReference;
            }

            /**
             * Sets the value of the doTReference property.
             * 
             * @param value
             *     allowed object is
             *     {@link JAXBElement }{@code <}{@link String }{@code >}
             *     
             */
            public void setDoTReference(JAXBElement<String> value) {
                this.doTReference = ((JAXBElement<String> ) value);
            }

            /**
             * Gets the value of the doTField1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDoTField1() {
                return doTField1;
            }

            /**
             * Sets the value of the doTField1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDoTField1(String value) {
                this.doTField1 = value;
            }

            /**
             * Gets the value of the doTField2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDoTField2() {
                return doTField2;
            }

            /**
             * Sets the value of the doTField2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDoTField2(String value) {
                this.doTField2 = value;
            }

            /**
             * Gets the value of the doTField3 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDoTField3() {
                return doTField3;
            }

            /**
             * Sets the value of the doTField3 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDoTField3(String value) {
                this.doTField3 = value;
            }

            /**
             * Gets the value of the doTField4 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDoTField4() {
                return doTField4;
            }

            /**
             * Sets the value of the doTField4 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDoTField4(String value) {
                this.doTField4 = value;
            }

            /**
             * Gets the value of the doTField5 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDoTField5() {
                return doTField5;
            }

            /**
             * Sets the value of the doTField5 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDoTField5(String value) {
                this.doTField5 = value;
            }

            /**
             * Gets the value of the doTField6 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDoTField6() {
                return doTField6;
            }

            /**
             * Sets the value of the doTField6 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDoTField6(String value) {
                this.doTField6 = value;
            }

            /**
             * Gets the value of the doTField7 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDoTField7() {
                return doTField7;
            }

            /**
             * Sets the value of the doTField7 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDoTField7(String value) {
                this.doTField7 = value;
            }

            /**
             * Gets the value of the doTField8 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDoTField8() {
                return doTField8;
            }

            /**
             * Sets the value of the doTField8 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDoTField8(String value) {
                this.doTField8 = value;
            }

            /**
             * Gets the value of the doTField9 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDoTField9() {
                return doTField9;
            }

            /**
             * Sets the value of the doTField9 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDoTField9(String value) {
                this.doTField9 = value;
            }

            /**
             * Gets the value of the doTField110 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDoTField110() {
                return doTField110;
            }

            /**
             * Sets the value of the doTField110 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDoTField110(String value) {
                this.doTField110 = value;
            }

        }

    }

}
