//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.messages;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.misys.tiplus2.apps.ti.service.common.GWRReservation;


/**
 * .
 * 
 * <p>Java class for ReservationRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReservationRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReservationRequestDetails" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRReservation" minOccurs="0"/>
 *         &lt;element name="ExtraDataFieldss" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ExtraDataFields" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReservationRequest", propOrder = {
    "reservationRequestDetails",
    "extraDataFieldss"
})
public class ReservationRequest {

    @XmlElement(name = "ReservationRequestDetails")
    protected GWRReservation reservationRequestDetails;
    @XmlElement(name = "ExtraDataFieldss")
    protected ReservationRequest.ExtraDataFieldss extraDataFieldss;

    /**
     * Gets the value of the reservationRequestDetails property.
     * 
     * @return
     *     possible object is
     *     {@link GWRReservation }
     *     
     */
    public GWRReservation getReservationRequestDetails() {
        return reservationRequestDetails;
    }

    /**
     * Sets the value of the reservationRequestDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRReservation }
     *     
     */
    public void setReservationRequestDetails(GWRReservation value) {
        this.reservationRequestDetails = value;
    }

    /**
     * Gets the value of the extraDataFieldss property.
     * 
     * @return
     *     possible object is
     *     {@link ReservationRequest.ExtraDataFieldss }
     *     
     */
    public ReservationRequest.ExtraDataFieldss getExtraDataFieldss() {
        return extraDataFieldss;
    }

    /**
     * Sets the value of the extraDataFieldss property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReservationRequest.ExtraDataFieldss }
     *     
     */
    public void setExtraDataFieldss(ReservationRequest.ExtraDataFieldss value) {
        this.extraDataFieldss = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ExtraDataFields" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "extraDataFields"
    })
    public static class ExtraDataFieldss {

        @XmlElement(name = "ExtraDataFields", required = true)
        protected List<ReservationRequest.ExtraDataFieldss.ExtraDataFields> extraDataFields;

        /**
         * Gets the value of the extraDataFields property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the extraDataFields property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExtraDataFields().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ReservationRequest.ExtraDataFieldss.ExtraDataFields }
         * 
         * 
         */
        public List<ReservationRequest.ExtraDataFieldss.ExtraDataFields> getExtraDataFields() {
            if (extraDataFields == null) {
                extraDataFields = new ArrayList<ReservationRequest.ExtraDataFieldss.ExtraDataFields>();
            }
            return this.extraDataFields;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "value"
        })
        public static class ExtraDataFields {

            @XmlElement(name = "Name")
            protected String name;
            @XmlElement(name = "Value")
            protected String value;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

        }

    }

}
