//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.messages;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.misys.tiplus2.apps.ti.service.common.EnigmaBoolean;
import com.misys.tiplus2.apps.ti.service.common.GWRChargeFrequency;
import com.misys.tiplus2.apps.ti.service.common.GWRChargeScheduleType;
import com.misys.tiplus2.apps.ti.service.common.GWRCustomer;
import com.misys.tiplus2.apps.ti.service.common.GWRInterestRateType;
import com.misys.tiplus2.apps.ti.service.common.GWRParty;
import com.misys.tiplus2.apps.ti.service.common.GWRPeriod;
import com.misys.tiplus2.apps.ti.service.common.GWRPeriodOrAmount;


/**
 * .
 * 
 * <p>Java class for STR001 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STR001">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:messages.service.ti.apps.tiplus2.misys.com}GatewaySystemTailoring">
 *       &lt;sequence>
 *         &lt;element name="Sender" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRParty" minOccurs="0"/>
 *         &lt;element name="TheirRef" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRReference" minOccurs="0"/>
 *         &lt;element name="Customer" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRCustomer" minOccurs="0"/>
 *         &lt;element name="ChargeID" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRReleaseTemplateId" minOccurs="0"/>
 *         &lt;element name="Narrative" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRChargeScheduleNarrative" minOccurs="0"/>
 *         &lt;element name="SchedType" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRChargeScheduleType" minOccurs="0"/>
 *         &lt;element name="Ccy" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRCurrency" minOccurs="0"/>
 *         &lt;element name="ChgsWaive" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRInteger" minOccurs="0"/>
 *         &lt;element name="MaxChgs" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRInteger" minOccurs="0"/>
 *         &lt;element name="Split" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRBool" minOccurs="0"/>
 *         &lt;element name="PerdAmt" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRPeriodOrAmount" minOccurs="0"/>
 *         &lt;element name="T1Period" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRPeriod" minOccurs="0"/>
 *         &lt;element name="T2Period" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRPeriod" minOccurs="0"/>
 *         &lt;element name="T3Period" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRPeriod" minOccurs="0"/>
 *         &lt;element name="T1Amt" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAmount" minOccurs="0"/>
 *         &lt;element name="T2Amt" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAmount" minOccurs="0"/>
 *         &lt;element name="T3Amt" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAmount" minOccurs="0"/>
 *         &lt;element name="T1Frq" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRChargeFrequency" minOccurs="0"/>
 *         &lt;element name="T2Frq" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRChargeFrequency" minOccurs="0"/>
 *         &lt;element name="T3Frq" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRChargeFrequency" minOccurs="0"/>
 *         &lt;element name="T4Frq" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRChargeFrequency" minOccurs="0"/>
 *         &lt;element name="PerdMinMax" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRBool" minOccurs="0"/>
 *         &lt;element name="MinMaxCcy" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRCurrency" minOccurs="0"/>
 *         &lt;element name="T1MinAmt" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAmount" minOccurs="0"/>
 *         &lt;element name="T1MaxAmt" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAmount" minOccurs="0"/>
 *         &lt;element name="T2MinAmt" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAmount" minOccurs="0"/>
 *         &lt;element name="T2MaxAmt" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAmount" minOccurs="0"/>
 *         &lt;element name="T3MinAmt" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAmount" minOccurs="0"/>
 *         &lt;element name="T3MaxAmt" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAmount" minOccurs="0"/>
 *         &lt;element name="T4MinAmt" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAmount" minOccurs="0"/>
 *         &lt;element name="T4MaxAmt" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAmount" minOccurs="0"/>
 *         &lt;element name="OverallMin" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAmount" minOccurs="0"/>
 *         &lt;element name="OverallMax" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAmount" minOccurs="0"/>
 *         &lt;element name="InterestType" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRInterestRateType" minOccurs="0"/>
 *         &lt;element name="IDB" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRInterestDaysBasis" minOccurs="0"/>
 *         &lt;element name="MinPeriod" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRPeriod" minOccurs="0"/>
 *         &lt;element name="T1BaseCode" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRBaseRateCode" minOccurs="0"/>
 *         &lt;element name="T1Diff" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDifferentialRate" minOccurs="0"/>
 *         &lt;element name="T1Rate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRRate" minOccurs="0"/>
 *         &lt;element name="T2BaseCode" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRBaseRateCode" minOccurs="0"/>
 *         &lt;element name="T2Diff" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDifferentialRate" minOccurs="0"/>
 *         &lt;element name="T2Rate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRRate" minOccurs="0"/>
 *         &lt;element name="T3BaseCode" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRBaseRateCode" minOccurs="0"/>
 *         &lt;element name="T3Diff" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDifferentialRate" minOccurs="0"/>
 *         &lt;element name="T3Rate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRRate" minOccurs="0"/>
 *         &lt;element name="T4BaseCode" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRBaseRateCode" minOccurs="0"/>
 *         &lt;element name="T4Diff" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDifferentialRate" minOccurs="0"/>
 *         &lt;element name="T4Rate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRRate" minOccurs="0"/>
 *         &lt;element name="TierAmt1" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAmount" minOccurs="0"/>
 *         &lt;element name="TierAmt2" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAmount" minOccurs="0"/>
 *         &lt;element name="TierAmt3" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAmount" minOccurs="0"/>
 *         &lt;element name="TierAmt4" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAmount" minOccurs="0"/>
 *         &lt;element name="T1Percent" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRRate" minOccurs="0"/>
 *         &lt;element name="T2Percent" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRRate" minOccurs="0"/>
 *         &lt;element name="T3Percent" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRRate" minOccurs="0"/>
 *         &lt;element name="T4Percent" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRRate" minOccurs="0"/>
 *         &lt;element name="ExpiryDate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDate" minOccurs="0"/>
 *         &lt;element name="StartDate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STR001", propOrder = {
    "sender",
    "theirRef",
    "customer",
    "chargeID",
    "narrative",
    "schedType",
    "ccy",
    "chgsWaive",
    "maxChgs",
    "split",
    "perdAmt",
    "t1Period",
    "t2Period",
    "t3Period",
    "t1Amt",
    "t2Amt",
    "t3Amt",
    "t1Frq",
    "t2Frq",
    "t3Frq",
    "t4Frq",
    "perdMinMax",
    "minMaxCcy",
    "t1MinAmt",
    "t1MaxAmt",
    "t2MinAmt",
    "t2MaxAmt",
    "t3MinAmt",
    "t3MaxAmt",
    "t4MinAmt",
    "t4MaxAmt",
    "overallMin",
    "overallMax",
    "interestType",
    "idb",
    "minPeriod",
    "t1BaseCode",
    "t1Diff",
    "t1Rate",
    "t2BaseCode",
    "t2Diff",
    "t2Rate",
    "t3BaseCode",
    "t3Diff",
    "t3Rate",
    "t4BaseCode",
    "t4Diff",
    "t4Rate",
    "tierAmt1",
    "tierAmt2",
    "tierAmt3",
    "tierAmt4",
    "t1Percent",
    "t2Percent",
    "t3Percent",
    "t4Percent",
    "expiryDate",
    "startDate"
})
public class STR001
    extends GatewaySystemTailoring
{

    @XmlElement(name = "Sender")
    protected GWRParty sender;
    @XmlElement(name = "TheirRef")
    protected String theirRef;
    @XmlElement(name = "Customer")
    protected GWRCustomer customer;
    @XmlElement(name = "ChargeID")
    protected String chargeID;
    @XmlElement(name = "Narrative")
    protected String narrative;
    @XmlElementRef(name = "SchedType", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<GWRChargeScheduleType> schedType;
    @XmlElement(name = "Ccy")
    protected String ccy;
    @XmlElementRef(name = "ChgsWaive", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Integer> chgsWaive;
    @XmlElementRef(name = "MaxChgs", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Integer> maxChgs;
    @XmlElement(name = "Split")
    protected EnigmaBoolean split;
    @XmlElement(name = "PerdAmt")
    protected GWRPeriodOrAmount perdAmt;
    @XmlElement(name = "T1Period")
    protected GWRPeriod t1Period;
    @XmlElement(name = "T2Period")
    protected GWRPeriod t2Period;
    @XmlElement(name = "T3Period")
    protected GWRPeriod t3Period;
    @XmlElementRef(name = "T1Amt", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Long> t1Amt;
    @XmlElementRef(name = "T2Amt", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Long> t2Amt;
    @XmlElementRef(name = "T3Amt", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Long> t3Amt;
    @XmlElementRef(name = "T1Frq", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<GWRChargeFrequency> t1Frq;
    @XmlElementRef(name = "T2Frq", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<GWRChargeFrequency> t2Frq;
    @XmlElementRef(name = "T3Frq", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<GWRChargeFrequency> t3Frq;
    @XmlElementRef(name = "T4Frq", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<GWRChargeFrequency> t4Frq;
    @XmlElement(name = "PerdMinMax")
    protected EnigmaBoolean perdMinMax;
    @XmlElement(name = "MinMaxCcy")
    protected String minMaxCcy;
    @XmlElementRef(name = "T1MinAmt", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Long> t1MinAmt;
    @XmlElementRef(name = "T1MaxAmt", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Long> t1MaxAmt;
    @XmlElementRef(name = "T2MinAmt", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Long> t2MinAmt;
    @XmlElementRef(name = "T2MaxAmt", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Long> t2MaxAmt;
    @XmlElementRef(name = "T3MinAmt", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Long> t3MinAmt;
    @XmlElementRef(name = "T3MaxAmt", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Long> t3MaxAmt;
    @XmlElementRef(name = "T4MinAmt", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Long> t4MinAmt;
    @XmlElementRef(name = "T4MaxAmt", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Long> t4MaxAmt;
    @XmlElementRef(name = "OverallMin", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Long> overallMin;
    @XmlElementRef(name = "OverallMax", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Long> overallMax;
    @XmlElementRef(name = "InterestType", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<GWRInterestRateType> interestType;
    @XmlElementRef(name = "IDB", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<String> idb;
    @XmlElement(name = "MinPeriod")
    protected GWRPeriod minPeriod;
    @XmlElement(name = "T1BaseCode")
    protected String t1BaseCode;
    @XmlElement(name = "T1Diff")
    protected String t1Diff;
    @XmlElement(name = "T1Rate")
    protected BigDecimal t1Rate;
    @XmlElement(name = "T2BaseCode")
    protected String t2BaseCode;
    @XmlElement(name = "T2Diff")
    protected String t2Diff;
    @XmlElement(name = "T2Rate")
    protected BigDecimal t2Rate;
    @XmlElement(name = "T3BaseCode")
    protected String t3BaseCode;
    @XmlElement(name = "T3Diff")
    protected String t3Diff;
    @XmlElement(name = "T3Rate")
    protected BigDecimal t3Rate;
    @XmlElement(name = "T4BaseCode")
    protected String t4BaseCode;
    @XmlElement(name = "T4Diff")
    protected String t4Diff;
    @XmlElement(name = "T4Rate")
    protected BigDecimal t4Rate;
    @XmlElementRef(name = "TierAmt1", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Long> tierAmt1;
    @XmlElementRef(name = "TierAmt2", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Long> tierAmt2;
    @XmlElementRef(name = "TierAmt3", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Long> tierAmt3;
    @XmlElementRef(name = "TierAmt4", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Long> tierAmt4;
    @XmlElement(name = "T1Percent")
    protected BigDecimal t1Percent;
    @XmlElement(name = "T2Percent")
    protected BigDecimal t2Percent;
    @XmlElement(name = "T3Percent")
    protected BigDecimal t3Percent;
    @XmlElement(name = "T4Percent")
    protected BigDecimal t4Percent;
    @XmlElementRef(name = "ExpiryDate", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> expiryDate;
    @XmlElementRef(name = "StartDate", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> startDate;

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link GWRParty }
     *     
     */
    public GWRParty getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRParty }
     *     
     */
    public void setSender(GWRParty value) {
        this.sender = value;
    }

    /**
     * Gets the value of the theirRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTheirRef() {
        return theirRef;
    }

    /**
     * Sets the value of the theirRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTheirRef(String value) {
        this.theirRef = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link GWRCustomer }
     *     
     */
    public GWRCustomer getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRCustomer }
     *     
     */
    public void setCustomer(GWRCustomer value) {
        this.customer = value;
    }

    /**
     * Gets the value of the chargeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeID() {
        return chargeID;
    }

    /**
     * Sets the value of the chargeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeID(String value) {
        this.chargeID = value;
    }

    /**
     * Gets the value of the narrative property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNarrative() {
        return narrative;
    }

    /**
     * Sets the value of the narrative property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNarrative(String value) {
        this.narrative = value;
    }

    /**
     * Gets the value of the schedType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GWRChargeScheduleType }{@code >}
     *     
     */
    public JAXBElement<GWRChargeScheduleType> getSchedType() {
        return schedType;
    }

    /**
     * Sets the value of the schedType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GWRChargeScheduleType }{@code >}
     *     
     */
    public void setSchedType(JAXBElement<GWRChargeScheduleType> value) {
        this.schedType = ((JAXBElement<GWRChargeScheduleType> ) value);
    }

    /**
     * Gets the value of the ccy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcy() {
        return ccy;
    }

    /**
     * Sets the value of the ccy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcy(String value) {
        this.ccy = value;
    }

    /**
     * Gets the value of the chgsWaive property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getChgsWaive() {
        return chgsWaive;
    }

    /**
     * Sets the value of the chgsWaive property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setChgsWaive(JAXBElement<Integer> value) {
        this.chgsWaive = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the maxChgs property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getMaxChgs() {
        return maxChgs;
    }

    /**
     * Sets the value of the maxChgs property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setMaxChgs(JAXBElement<Integer> value) {
        this.maxChgs = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the split property.
     * 
     * @return
     *     possible object is
     *     {@link EnigmaBoolean }
     *     
     */
    public EnigmaBoolean getSplit() {
        return split;
    }

    /**
     * Sets the value of the split property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnigmaBoolean }
     *     
     */
    public void setSplit(EnigmaBoolean value) {
        this.split = value;
    }

    /**
     * Gets the value of the perdAmt property.
     * 
     * @return
     *     possible object is
     *     {@link GWRPeriodOrAmount }
     *     
     */
    public GWRPeriodOrAmount getPerdAmt() {
        return perdAmt;
    }

    /**
     * Sets the value of the perdAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRPeriodOrAmount }
     *     
     */
    public void setPerdAmt(GWRPeriodOrAmount value) {
        this.perdAmt = value;
    }

    /**
     * Gets the value of the t1Period property.
     * 
     * @return
     *     possible object is
     *     {@link GWRPeriod }
     *     
     */
    public GWRPeriod getT1Period() {
        return t1Period;
    }

    /**
     * Sets the value of the t1Period property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRPeriod }
     *     
     */
    public void setT1Period(GWRPeriod value) {
        this.t1Period = value;
    }

    /**
     * Gets the value of the t2Period property.
     * 
     * @return
     *     possible object is
     *     {@link GWRPeriod }
     *     
     */
    public GWRPeriod getT2Period() {
        return t2Period;
    }

    /**
     * Sets the value of the t2Period property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRPeriod }
     *     
     */
    public void setT2Period(GWRPeriod value) {
        this.t2Period = value;
    }

    /**
     * Gets the value of the t3Period property.
     * 
     * @return
     *     possible object is
     *     {@link GWRPeriod }
     *     
     */
    public GWRPeriod getT3Period() {
        return t3Period;
    }

    /**
     * Sets the value of the t3Period property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRPeriod }
     *     
     */
    public void setT3Period(GWRPeriod value) {
        this.t3Period = value;
    }

    /**
     * Gets the value of the t1Amt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getT1Amt() {
        return t1Amt;
    }

    /**
     * Sets the value of the t1Amt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setT1Amt(JAXBElement<Long> value) {
        this.t1Amt = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the t2Amt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getT2Amt() {
        return t2Amt;
    }

    /**
     * Sets the value of the t2Amt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setT2Amt(JAXBElement<Long> value) {
        this.t2Amt = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the t3Amt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getT3Amt() {
        return t3Amt;
    }

    /**
     * Sets the value of the t3Amt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setT3Amt(JAXBElement<Long> value) {
        this.t3Amt = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the t1Frq property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GWRChargeFrequency }{@code >}
     *     
     */
    public JAXBElement<GWRChargeFrequency> getT1Frq() {
        return t1Frq;
    }

    /**
     * Sets the value of the t1Frq property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GWRChargeFrequency }{@code >}
     *     
     */
    public void setT1Frq(JAXBElement<GWRChargeFrequency> value) {
        this.t1Frq = ((JAXBElement<GWRChargeFrequency> ) value);
    }

    /**
     * Gets the value of the t2Frq property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GWRChargeFrequency }{@code >}
     *     
     */
    public JAXBElement<GWRChargeFrequency> getT2Frq() {
        return t2Frq;
    }

    /**
     * Sets the value of the t2Frq property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GWRChargeFrequency }{@code >}
     *     
     */
    public void setT2Frq(JAXBElement<GWRChargeFrequency> value) {
        this.t2Frq = ((JAXBElement<GWRChargeFrequency> ) value);
    }

    /**
     * Gets the value of the t3Frq property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GWRChargeFrequency }{@code >}
     *     
     */
    public JAXBElement<GWRChargeFrequency> getT3Frq() {
        return t3Frq;
    }

    /**
     * Sets the value of the t3Frq property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GWRChargeFrequency }{@code >}
     *     
     */
    public void setT3Frq(JAXBElement<GWRChargeFrequency> value) {
        this.t3Frq = ((JAXBElement<GWRChargeFrequency> ) value);
    }

    /**
     * Gets the value of the t4Frq property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GWRChargeFrequency }{@code >}
     *     
     */
    public JAXBElement<GWRChargeFrequency> getT4Frq() {
        return t4Frq;
    }

    /**
     * Sets the value of the t4Frq property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GWRChargeFrequency }{@code >}
     *     
     */
    public void setT4Frq(JAXBElement<GWRChargeFrequency> value) {
        this.t4Frq = ((JAXBElement<GWRChargeFrequency> ) value);
    }

    /**
     * Gets the value of the perdMinMax property.
     * 
     * @return
     *     possible object is
     *     {@link EnigmaBoolean }
     *     
     */
    public EnigmaBoolean getPerdMinMax() {
        return perdMinMax;
    }

    /**
     * Sets the value of the perdMinMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnigmaBoolean }
     *     
     */
    public void setPerdMinMax(EnigmaBoolean value) {
        this.perdMinMax = value;
    }

    /**
     * Gets the value of the minMaxCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinMaxCcy() {
        return minMaxCcy;
    }

    /**
     * Sets the value of the minMaxCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinMaxCcy(String value) {
        this.minMaxCcy = value;
    }

    /**
     * Gets the value of the t1MinAmt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getT1MinAmt() {
        return t1MinAmt;
    }

    /**
     * Sets the value of the t1MinAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setT1MinAmt(JAXBElement<Long> value) {
        this.t1MinAmt = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the t1MaxAmt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getT1MaxAmt() {
        return t1MaxAmt;
    }

    /**
     * Sets the value of the t1MaxAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setT1MaxAmt(JAXBElement<Long> value) {
        this.t1MaxAmt = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the t2MinAmt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getT2MinAmt() {
        return t2MinAmt;
    }

    /**
     * Sets the value of the t2MinAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setT2MinAmt(JAXBElement<Long> value) {
        this.t2MinAmt = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the t2MaxAmt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getT2MaxAmt() {
        return t2MaxAmt;
    }

    /**
     * Sets the value of the t2MaxAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setT2MaxAmt(JAXBElement<Long> value) {
        this.t2MaxAmt = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the t3MinAmt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getT3MinAmt() {
        return t3MinAmt;
    }

    /**
     * Sets the value of the t3MinAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setT3MinAmt(JAXBElement<Long> value) {
        this.t3MinAmt = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the t3MaxAmt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getT3MaxAmt() {
        return t3MaxAmt;
    }

    /**
     * Sets the value of the t3MaxAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setT3MaxAmt(JAXBElement<Long> value) {
        this.t3MaxAmt = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the t4MinAmt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getT4MinAmt() {
        return t4MinAmt;
    }

    /**
     * Sets the value of the t4MinAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setT4MinAmt(JAXBElement<Long> value) {
        this.t4MinAmt = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the t4MaxAmt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getT4MaxAmt() {
        return t4MaxAmt;
    }

    /**
     * Sets the value of the t4MaxAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setT4MaxAmt(JAXBElement<Long> value) {
        this.t4MaxAmt = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the overallMin property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getOverallMin() {
        return overallMin;
    }

    /**
     * Sets the value of the overallMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setOverallMin(JAXBElement<Long> value) {
        this.overallMin = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the overallMax property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getOverallMax() {
        return overallMax;
    }

    /**
     * Sets the value of the overallMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setOverallMax(JAXBElement<Long> value) {
        this.overallMax = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the interestType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GWRInterestRateType }{@code >}
     *     
     */
    public JAXBElement<GWRInterestRateType> getInterestType() {
        return interestType;
    }

    /**
     * Sets the value of the interestType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GWRInterestRateType }{@code >}
     *     
     */
    public void setInterestType(JAXBElement<GWRInterestRateType> value) {
        this.interestType = ((JAXBElement<GWRInterestRateType> ) value);
    }

    /**
     * Gets the value of the idb property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getIDB() {
        return idb;
    }

    /**
     * Sets the value of the idb property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setIDB(JAXBElement<String> value) {
        this.idb = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the minPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link GWRPeriod }
     *     
     */
    public GWRPeriod getMinPeriod() {
        return minPeriod;
    }

    /**
     * Sets the value of the minPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRPeriod }
     *     
     */
    public void setMinPeriod(GWRPeriod value) {
        this.minPeriod = value;
    }

    /**
     * Gets the value of the t1BaseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getT1BaseCode() {
        return t1BaseCode;
    }

    /**
     * Sets the value of the t1BaseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setT1BaseCode(String value) {
        this.t1BaseCode = value;
    }

    /**
     * Gets the value of the t1Diff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getT1Diff() {
        return t1Diff;
    }

    /**
     * Sets the value of the t1Diff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setT1Diff(String value) {
        this.t1Diff = value;
    }

    /**
     * Gets the value of the t1Rate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT1Rate() {
        return t1Rate;
    }

    /**
     * Sets the value of the t1Rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT1Rate(BigDecimal value) {
        this.t1Rate = value;
    }

    /**
     * Gets the value of the t2BaseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getT2BaseCode() {
        return t2BaseCode;
    }

    /**
     * Sets the value of the t2BaseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setT2BaseCode(String value) {
        this.t2BaseCode = value;
    }

    /**
     * Gets the value of the t2Diff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getT2Diff() {
        return t2Diff;
    }

    /**
     * Sets the value of the t2Diff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setT2Diff(String value) {
        this.t2Diff = value;
    }

    /**
     * Gets the value of the t2Rate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT2Rate() {
        return t2Rate;
    }

    /**
     * Sets the value of the t2Rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT2Rate(BigDecimal value) {
        this.t2Rate = value;
    }

    /**
     * Gets the value of the t3BaseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getT3BaseCode() {
        return t3BaseCode;
    }

    /**
     * Sets the value of the t3BaseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setT3BaseCode(String value) {
        this.t3BaseCode = value;
    }

    /**
     * Gets the value of the t3Diff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getT3Diff() {
        return t3Diff;
    }

    /**
     * Sets the value of the t3Diff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setT3Diff(String value) {
        this.t3Diff = value;
    }

    /**
     * Gets the value of the t3Rate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT3Rate() {
        return t3Rate;
    }

    /**
     * Sets the value of the t3Rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT3Rate(BigDecimal value) {
        this.t3Rate = value;
    }

    /**
     * Gets the value of the t4BaseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getT4BaseCode() {
        return t4BaseCode;
    }

    /**
     * Sets the value of the t4BaseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setT4BaseCode(String value) {
        this.t4BaseCode = value;
    }

    /**
     * Gets the value of the t4Diff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getT4Diff() {
        return t4Diff;
    }

    /**
     * Sets the value of the t4Diff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setT4Diff(String value) {
        this.t4Diff = value;
    }

    /**
     * Gets the value of the t4Rate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT4Rate() {
        return t4Rate;
    }

    /**
     * Sets the value of the t4Rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT4Rate(BigDecimal value) {
        this.t4Rate = value;
    }

    /**
     * Gets the value of the tierAmt1 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getTierAmt1() {
        return tierAmt1;
    }

    /**
     * Sets the value of the tierAmt1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setTierAmt1(JAXBElement<Long> value) {
        this.tierAmt1 = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the tierAmt2 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getTierAmt2() {
        return tierAmt2;
    }

    /**
     * Sets the value of the tierAmt2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setTierAmt2(JAXBElement<Long> value) {
        this.tierAmt2 = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the tierAmt3 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getTierAmt3() {
        return tierAmt3;
    }

    /**
     * Sets the value of the tierAmt3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setTierAmt3(JAXBElement<Long> value) {
        this.tierAmt3 = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the tierAmt4 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getTierAmt4() {
        return tierAmt4;
    }

    /**
     * Sets the value of the tierAmt4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setTierAmt4(JAXBElement<Long> value) {
        this.tierAmt4 = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the t1Percent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT1Percent() {
        return t1Percent;
    }

    /**
     * Sets the value of the t1Percent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT1Percent(BigDecimal value) {
        this.t1Percent = value;
    }

    /**
     * Gets the value of the t2Percent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT2Percent() {
        return t2Percent;
    }

    /**
     * Sets the value of the t2Percent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT2Percent(BigDecimal value) {
        this.t2Percent = value;
    }

    /**
     * Gets the value of the t3Percent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT3Percent() {
        return t3Percent;
    }

    /**
     * Sets the value of the t3Percent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT3Percent(BigDecimal value) {
        this.t3Percent = value;
    }

    /**
     * Gets the value of the t4Percent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT4Percent() {
        return t4Percent;
    }

    /**
     * Sets the value of the t4Percent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT4Percent(BigDecimal value) {
        this.t4Percent = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setExpiryDate(JAXBElement<XMLGregorianCalendar> value) {
        this.expiryDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setStartDate(JAXBElement<XMLGregorianCalendar> value) {
        this.startDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

}
