//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Account officer.
 * 
 * <p>Java class for STRAccountOfficer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STRAccountOfficer">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:messages.service.ti.apps.tiplus2.misys.com}GatewayStatic">
 *       &lt;sequence>
 *         &lt;element name="Code" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAccountOfficerCode" minOccurs="0"/>
 *         &lt;element name="Description" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRFullName" minOccurs="0"/>
 *         &lt;element name="DepartmentCode" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRDepartmentCode" minOccurs="0"/>
 *         &lt;element name="ManagerType" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRManagerType" minOccurs="0"/>
 *         &lt;element name="TransferMethod" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRTransferMethod" minOccurs="0"/>
 *         &lt;element name="Language" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRLanguage" minOccurs="0"/>
 *         &lt;element name="NameAndAddress" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRNameAndAddress" minOccurs="0"/>
 *         &lt;element name="ZIP" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRZip" minOccurs="0"/>
 *         &lt;element name="Phone" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRPhoneNumber" minOccurs="0"/>
 *         &lt;element name="Extension" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRPhoneExtension" minOccurs="0"/>
 *         &lt;element name="Fax" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRFaxNumber" minOccurs="0"/>
 *         &lt;element name="Telex" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRTelex" minOccurs="0"/>
 *         &lt;element name="TelexAnswerBack" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRTelexAnswerBack" minOccurs="0"/>
 *         &lt;element name="EmailAddress" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWREmailAddress2" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STRAccountOfficer", propOrder = {
    "code",
    "description",
    "departmentCode",
    "managerType",
    "transferMethod",
    "language",
    "nameAndAddress",
    "zip",
    "phone",
    "extension",
    "fax",
    "telex",
    "telexAnswerBack",
    "emailAddress"
})
public class STRAccountOfficer
    extends GatewayStatic
{

    @XmlElement(name = "Code")
    protected String code;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "DepartmentCode")
    protected String departmentCode;
    @XmlElement(name = "ManagerType")
    protected String managerType;
    @XmlElement(name = "TransferMethod")
    protected String transferMethod;
    @XmlElement(name = "Language")
    protected String language;
    @XmlElement(name = "NameAndAddress")
    protected String nameAndAddress;
    @XmlElement(name = "ZIP")
    protected String zip;
    @XmlElement(name = "Phone")
    protected String phone;
    @XmlElement(name = "Extension")
    protected String extension;
    @XmlElement(name = "Fax")
    protected String fax;
    @XmlElement(name = "Telex")
    protected String telex;
    @XmlElement(name = "TelexAnswerBack")
    protected String telexAnswerBack;
    @XmlElement(name = "EmailAddress")
    protected String emailAddress;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the departmentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * Sets the value of the departmentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartmentCode(String value) {
        this.departmentCode = value;
    }

    /**
     * Gets the value of the managerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagerType() {
        return managerType;
    }

    /**
     * Sets the value of the managerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagerType(String value) {
        this.managerType = value;
    }

    /**
     * Gets the value of the transferMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferMethod() {
        return transferMethod;
    }

    /**
     * Sets the value of the transferMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferMethod(String value) {
        this.transferMethod = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the nameAndAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameAndAddress() {
        return nameAndAddress;
    }

    /**
     * Sets the value of the nameAndAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameAndAddress(String value) {
        this.nameAndAddress = value;
    }

    /**
     * Gets the value of the zip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZIP() {
        return zip;
    }

    /**
     * Sets the value of the zip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZIP(String value) {
        this.zip = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtension(String value) {
        this.extension = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFax(String value) {
        this.fax = value;
    }

    /**
     * Gets the value of the telex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelex() {
        return telex;
    }

    /**
     * Sets the value of the telex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelex(String value) {
        this.telex = value;
    }

    /**
     * Gets the value of the telexAnswerBack property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelexAnswerBack() {
        return telexAnswerBack;
    }

    /**
     * Sets the value of the telexAnswerBack property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelexAnswerBack(String value) {
        this.telexAnswerBack = value;
    }

    /**
     * Gets the value of the emailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress(String value) {
        this.emailAddress = value;
    }

}
