//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Charge code .
 * 
 * <p>Java class for STRChargeCode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STRChargeCode">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:messages.service.ti.apps.tiplus2.misys.com}GatewayStatic">
 *       &lt;sequence>
 *         &lt;element name="Code" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRChargeCodeKey" minOccurs="0"/>
 *         &lt;element name="Description" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRFullName" minOccurs="0"/>
 *         &lt;element name="ShortNameAbbreviation" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRChargeCodeAbbreviation" minOccurs="0"/>
 *         &lt;element name="AccountType" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRAccountType" minOccurs="0"/>
 *         &lt;element name="CreditTransactionCode" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRTransactionCode" minOccurs="0"/>
 *         &lt;element name="DebitTransactionCode" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRTransactionCode" minOccurs="0"/>
 *         &lt;element name="CategoryCode" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRCategoryCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STRChargeCode", propOrder = {
    "code",
    "description",
    "shortNameAbbreviation",
    "accountType",
    "creditTransactionCode",
    "debitTransactionCode",
    "categoryCode"
})
public class STRChargeCode
    extends GatewayStatic
{

    @XmlElement(name = "Code")
    protected String code;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "ShortNameAbbreviation")
    protected String shortNameAbbreviation;
    @XmlElement(name = "AccountType")
    protected String accountType;
    @XmlElement(name = "CreditTransactionCode")
    protected String creditTransactionCode;
    @XmlElement(name = "DebitTransactionCode")
    protected String debitTransactionCode;
    @XmlElement(name = "CategoryCode")
    protected String categoryCode;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the shortNameAbbreviation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortNameAbbreviation() {
        return shortNameAbbreviation;
    }

    /**
     * Sets the value of the shortNameAbbreviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortNameAbbreviation(String value) {
        this.shortNameAbbreviation = value;
    }

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountType(String value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the creditTransactionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditTransactionCode() {
        return creditTransactionCode;
    }

    /**
     * Sets the value of the creditTransactionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditTransactionCode(String value) {
        this.creditTransactionCode = value;
    }

    /**
     * Gets the value of the debitTransactionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebitTransactionCode() {
        return debitTransactionCode;
    }

    /**
     * Sets the value of the debitTransactionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebitTransactionCode(String value) {
        this.debitTransactionCode = value;
    }

    /**
     * Gets the value of the categoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryCode() {
        return categoryCode;
    }

    /**
     * Sets the value of the categoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryCode(String value) {
        this.categoryCode = value;
    }

}
