//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * CustomerMnmChange documentation.
 * 
 * <p>Java class for STRCustomerMnemonic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STRCustomerMnemonic">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:messages.service.ti.apps.tiplus2.misys.com}GatewayDataUpdateDefinition">
 *       &lt;sequence>
 *         &lt;element name="SourceBankingBusiness" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRMainBankingEntity" minOccurs="0"/>
 *         &lt;element name="OldCustomerMnemonic" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRCustomerMnemonic" minOccurs="0"/>
 *         &lt;element name="NewCustomerMnemonic" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRCustomerMnemonic" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STRCustomerMnemonic", propOrder = {
    "sourceBankingBusiness",
    "oldCustomerMnemonic",
    "newCustomerMnemonic"
})
public class STRCustomerMnemonic
    extends GatewayDataUpdateDefinition
{

    @XmlElement(name = "SourceBankingBusiness")
    protected String sourceBankingBusiness;
    @XmlElement(name = "OldCustomerMnemonic")
    protected String oldCustomerMnemonic;
    @XmlElement(name = "NewCustomerMnemonic")
    protected String newCustomerMnemonic;

    /**
     * Gets the value of the sourceBankingBusiness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceBankingBusiness() {
        return sourceBankingBusiness;
    }

    /**
     * Sets the value of the sourceBankingBusiness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceBankingBusiness(String value) {
        this.sourceBankingBusiness = value;
    }

    /**
     * Gets the value of the oldCustomerMnemonic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldCustomerMnemonic() {
        return oldCustomerMnemonic;
    }

    /**
     * Sets the value of the oldCustomerMnemonic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldCustomerMnemonic(String value) {
        this.oldCustomerMnemonic = value;
    }

    /**
     * Gets the value of the newCustomerMnemonic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewCustomerMnemonic() {
        return newCustomerMnemonic;
    }

    /**
     * Sets the value of the newCustomerMnemonic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewCustomerMnemonic(String value) {
        this.newCustomerMnemonic = value;
    }

}
