//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Code description.
 * 
 * <p>Java class for STRCodeDescriptions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STRCodeDescriptions">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:messages.service.ti.apps.tiplus2.misys.com}GatewayStatic">
 *       &lt;sequence>
 *         &lt;element name="Language" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRLanguage" minOccurs="0"/>
 *         &lt;element name="TypeCode" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRCodeDescriptionTypeCode" minOccurs="0"/>
 *         &lt;element name="EntryIdent" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRCodeDescriptionEntryIdent" minOccurs="0"/>
 *         &lt;element name="Description" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRCodeDescriptionDescription" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STRCodeDescriptions", propOrder = {
    "language",
    "typeCode",
    "entryIdent",
    "description"
})
public class STRCodeDescriptions
    extends GatewayStatic
{

    @XmlElement(name = "Language")
    protected String language;
    @XmlElement(name = "TypeCode")
    protected String typeCode;
    @XmlElement(name = "EntryIdent")
    protected String entryIdent;
    @XmlElement(name = "Description")
    protected String description;

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * Sets the value of the typeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeCode(String value) {
        this.typeCode = value;
    }

    /**
     * Gets the value of the entryIdent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryIdent() {
        return entryIdent;
    }

    /**
     * Sets the value of the entryIdent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryIdent(String value) {
        this.entryIdent = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
