//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.misys.tiplus2.apps.ti.service.common.GWRExternalService;


/**
 * External service definition .
 * 
 * <p>Java class for STRExternalServiceDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STRExternalServiceDefinition">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:messages.service.ti.apps.tiplus2.misys.com}GatewayStatic">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRExternalServiceID" minOccurs="0"/>
 *         &lt;element name="ExternalServiceType" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRExternalService" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STRExternalServiceDefinition", propOrder = {
    "id",
    "externalServiceType"
})
public class STRExternalServiceDefinition
    extends GatewayStatic
{

    @XmlElement(name = "ID")
    protected String id;
    @XmlElement(name = "ExternalServiceType")
    protected GWRExternalService externalServiceType;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the externalServiceType property.
     * 
     * @return
     *     possible object is
     *     {@link GWRExternalService }
     *     
     */
    public GWRExternalService getExternalServiceType() {
        return externalServiceType;
    }

    /**
     * Sets the value of the externalServiceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRExternalService }
     *     
     */
    public void setExternalServiceType(GWRExternalService value) {
        this.externalServiceType = value;
    }

}
