//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.misys.tiplus2.apps.ti.service.common.EnigmaBoolean;
import com.misys.tiplus2.apps.ti.service.common.GWRMasterEventMap;


/**
 * Orchestration.
 * 
 * <p>Java class for STROrchestration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STROrchestration">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:messages.service.ti.apps.tiplus2.misys.com}GatewaySystemTailoring">
 *       &lt;sequence>
 *         &lt;element name="InUse" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRBool" minOccurs="0"/>
 *         &lt;element name="ParameterSet" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRParameterSet" minOccurs="0"/>
 *         &lt;element name="MasterEventMap" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRMasterEventMap" minOccurs="0"/>
 *         &lt;element name="OrchestrationTemplate" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWROrchestrationTemplate" minOccurs="0"/>
 *         &lt;element name="InitialStep" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWROrchestrationStep" minOccurs="0"/>
 *         &lt;element name="InitialStepFromSwift" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWROrchestrationStep" minOccurs="0"/>
 *         &lt;element name="InitialStepFromBatch" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWROrchestrationStep" minOccurs="0"/>
 *         &lt;element name="InitialStepFromGateway" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWROrchestrationStep" minOccurs="0"/>
 *         &lt;element name="RejectStepFromSwift" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWROrchestrationStep" minOccurs="0"/>
 *         &lt;element name="RejectStepFromBatch" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWROrchestrationStep" minOccurs="0"/>
 *         &lt;element name="RejectStepFromGateway" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWROrchestrationStep" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STROrchestration", propOrder = {
    "inUse",
    "parameterSet",
    "masterEventMap",
    "orchestrationTemplate",
    "initialStep",
    "initialStepFromSwift",
    "initialStepFromBatch",
    "initialStepFromGateway",
    "rejectStepFromSwift",
    "rejectStepFromBatch",
    "rejectStepFromGateway"
})
public class STROrchestration
    extends GatewaySystemTailoring
{

    @XmlElement(name = "InUse")
    protected EnigmaBoolean inUse;
    @XmlElement(name = "ParameterSet")
    protected String parameterSet;
    @XmlElement(name = "MasterEventMap")
    protected GWRMasterEventMap masterEventMap;
    @XmlElement(name = "OrchestrationTemplate")
    protected String orchestrationTemplate;
    @XmlElement(name = "InitialStep")
    protected String initialStep;
    @XmlElement(name = "InitialStepFromSwift")
    protected String initialStepFromSwift;
    @XmlElement(name = "InitialStepFromBatch")
    protected String initialStepFromBatch;
    @XmlElement(name = "InitialStepFromGateway")
    protected String initialStepFromGateway;
    @XmlElement(name = "RejectStepFromSwift")
    protected String rejectStepFromSwift;
    @XmlElement(name = "RejectStepFromBatch")
    protected String rejectStepFromBatch;
    @XmlElement(name = "RejectStepFromGateway")
    protected String rejectStepFromGateway;

    /**
     * Gets the value of the inUse property.
     * 
     * @return
     *     possible object is
     *     {@link EnigmaBoolean }
     *     
     */
    public EnigmaBoolean getInUse() {
        return inUse;
    }

    /**
     * Sets the value of the inUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnigmaBoolean }
     *     
     */
    public void setInUse(EnigmaBoolean value) {
        this.inUse = value;
    }

    /**
     * Gets the value of the parameterSet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameterSet() {
        return parameterSet;
    }

    /**
     * Sets the value of the parameterSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameterSet(String value) {
        this.parameterSet = value;
    }

    /**
     * Gets the value of the masterEventMap property.
     * 
     * @return
     *     possible object is
     *     {@link GWRMasterEventMap }
     *     
     */
    public GWRMasterEventMap getMasterEventMap() {
        return masterEventMap;
    }

    /**
     * Sets the value of the masterEventMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRMasterEventMap }
     *     
     */
    public void setMasterEventMap(GWRMasterEventMap value) {
        this.masterEventMap = value;
    }

    /**
     * Gets the value of the orchestrationTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrchestrationTemplate() {
        return orchestrationTemplate;
    }

    /**
     * Sets the value of the orchestrationTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrchestrationTemplate(String value) {
        this.orchestrationTemplate = value;
    }

    /**
     * Gets the value of the initialStep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialStep() {
        return initialStep;
    }

    /**
     * Sets the value of the initialStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialStep(String value) {
        this.initialStep = value;
    }

    /**
     * Gets the value of the initialStepFromSwift property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialStepFromSwift() {
        return initialStepFromSwift;
    }

    /**
     * Sets the value of the initialStepFromSwift property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialStepFromSwift(String value) {
        this.initialStepFromSwift = value;
    }

    /**
     * Gets the value of the initialStepFromBatch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialStepFromBatch() {
        return initialStepFromBatch;
    }

    /**
     * Sets the value of the initialStepFromBatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialStepFromBatch(String value) {
        this.initialStepFromBatch = value;
    }

    /**
     * Gets the value of the initialStepFromGateway property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialStepFromGateway() {
        return initialStepFromGateway;
    }

    /**
     * Sets the value of the initialStepFromGateway property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialStepFromGateway(String value) {
        this.initialStepFromGateway = value;
    }

    /**
     * Gets the value of the rejectStepFromSwift property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRejectStepFromSwift() {
        return rejectStepFromSwift;
    }

    /**
     * Sets the value of the rejectStepFromSwift property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRejectStepFromSwift(String value) {
        this.rejectStepFromSwift = value;
    }

    /**
     * Gets the value of the rejectStepFromBatch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRejectStepFromBatch() {
        return rejectStepFromBatch;
    }

    /**
     * Sets the value of the rejectStepFromBatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRejectStepFromBatch(String value) {
        this.rejectStepFromBatch = value;
    }

    /**
     * Gets the value of the rejectStepFromGateway property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRejectStepFromGateway() {
        return rejectStepFromGateway;
    }

    /**
     * Sets the value of the rejectStepFromGateway property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRejectStepFromGateway(String value) {
        this.rejectStepFromGateway = value;
    }

}
