//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.22 at 03:37:05 PM IST 
//


package com.misys.tiplus2.apps.ti.service.messages;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import com.misys.tiplus2.apps.ti.service.common.GWRCriteria;
import com.misys.tiplus2.apps.ti.service.common.GWRMapToSelector;


/**
 * .
 * 
 * <p>Java class for STRTeamEventMap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STRTeamEventMap">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:messages.service.ti.apps.tiplus2.misys.com}GatewaySystemTailoring">
 *       &lt;sequence>
 *         &lt;element name="Product" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRProduct" minOccurs="0"/>
 *         &lt;element name="EventType" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWREventType" minOccurs="0"/>
 *         &lt;element name="OrchestrationStep" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWROrchestrationStep" minOccurs="0"/>
 *         &lt;element name="StepTypeSequence" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRInteger" minOccurs="0"/>
 *         &lt;element name="MapToSelector" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRMapToSelector" minOccurs="0"/>
 *         &lt;element name="Team" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRTeam" minOccurs="0"/>
 *         &lt;element name="User" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRUser" minOccurs="0"/>
 *         &lt;element name="Criteria" type="{urn:common.service.ti.apps.tiplus2.misys.com}GWRCriteria" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STRTeamEventMap", propOrder = {
    "product",
    "eventType",
    "orchestrationStep",
    "stepTypeSequence",
    "mapToSelector",
    "team",
    "user",
    "criteria"
})
public class STRTeamEventMap
    extends GatewaySystemTailoring
{

    @XmlElement(name = "Product")
    protected String product;
    @XmlElement(name = "EventType")
    protected String eventType;
    @XmlElement(name = "OrchestrationStep")
    protected String orchestrationStep;
    @XmlElementRef(name = "StepTypeSequence", namespace = "urn:messages.service.ti.apps.tiplus2.misys.com", type = JAXBElement.class)
    protected JAXBElement<Integer> stepTypeSequence;
    @XmlElement(name = "MapToSelector")
    protected GWRMapToSelector mapToSelector;
    @XmlElement(name = "Team")
    protected String team;
    @XmlElement(name = "User")
    protected String user;
    @XmlElement(name = "Criteria")
    protected GWRCriteria criteria;

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProduct(String value) {
        this.product = value;
    }

    /**
     * Gets the value of the eventType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * Sets the value of the eventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventType(String value) {
        this.eventType = value;
    }

    /**
     * Gets the value of the orchestrationStep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrchestrationStep() {
        return orchestrationStep;
    }

    /**
     * Sets the value of the orchestrationStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrchestrationStep(String value) {
        this.orchestrationStep = value;
    }

    /**
     * Gets the value of the stepTypeSequence property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getStepTypeSequence() {
        return stepTypeSequence;
    }

    /**
     * Sets the value of the stepTypeSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setStepTypeSequence(JAXBElement<Integer> value) {
        this.stepTypeSequence = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the mapToSelector property.
     * 
     * @return
     *     possible object is
     *     {@link GWRMapToSelector }
     *     
     */
    public GWRMapToSelector getMapToSelector() {
        return mapToSelector;
    }

    /**
     * Sets the value of the mapToSelector property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRMapToSelector }
     *     
     */
    public void setMapToSelector(GWRMapToSelector value) {
        this.mapToSelector = value;
    }

    /**
     * Gets the value of the team property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeam() {
        return team;
    }

    /**
     * Sets the value of the team property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeam(String value) {
        this.team = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the criteria property.
     * 
     * @return
     *     possible object is
     *     {@link GWRCriteria }
     *     
     */
    public GWRCriteria getCriteria() {
        return criteria;
    }

    /**
     * Sets the value of the criteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link GWRCriteria }
     *     
     */
    public void setCriteria(GWRCriteria value) {
        this.criteria = value;
    }

}
