SELECT CASE WHEN EXPANC='V' THEN M.NPRCUSTMNM ELSE M.PRICUSTMNM END  AS customerid FROM   
 MASTER M, FNCEMASTER F, INVMASTER I, SCFPROGRAM S, SCFCPARTY P, ETT_CLF_PROGRAMPARAMETERS PP   
 WHERE TRIM(S.ID)=TRIM(PP.PROIDEN) AND  MASTER_REF='{referenceNumber}' 
 AND M.KEY97=F.KEY97  AND I.FINCE_EV=F.FINCEEVKEY AND S.KEY97=I.PROGRAMME AND P.PROGRAMME=S.KEY97  
 AND P.CPARTY = CASE WHEN S.PROG_TYPE ='B' THEN M.NPRCUSTMNM ELSE M.PRICUSTMNM END   